### ISSUE TITLE
Stylus, allow --include-css

### ISSUE THREAD

**Issue by DAddYE** [jenius/roots#175]
Would be nice if you can activate that option, so in our styl we can
include vanilla css.

Thanks!

**Comment by oompt** [comment]
Where are the docs for this? I looked at roots.cx/docs but I don't see anything explicitly about the API.

**Comment by oompt** [comment]
For everyone's edification: 

![the picture](http://f.cl.ly/items/1S3p3P2a0D1D1F3v2g3T/Image%202015-10-14%20at%2011.06.30%20AM.png)

(Don't forget to re-compile after making changes to app.coffee)

**Comment by jenius** [comment]
Hi, sorry for not responding quicker, I have had limited internet. Thanks for posting this solution and sorry you had to figure this out!

**Comment by oompt** [comment]
No worries. :)
