### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by notslang** [jenius/roots#189]
This isn't something that we should focus on _right_ now, but we should get around to it pretty soon. So i'm adding this as a long-term todo.

**Comment by Leeds-eBooks** [comment]
@jenius Has any progress been made on the extension? I'm interested in having a go myself, but I don't want to duplicate work.

**Comment by jenius** [comment]
Nope, not yet. I may be missing an easier way to do it, but in my estimation an extension like this requires a very complex mod to the central roots compile pipeline. By all means feel free to take a crack at it though!

**Comment by Leeds-eBooks** [comment]
I've actually got something working! It has one major caveat currently, and it's written very much to my specific use-case, but it could easily be made public-ready by swapping out some hard-coded values for user options. The caveat is that I have no idea how to make this work with `roots-records` template views.

What it essentially does is take all your jade files, then for each language yaml file you have in `./i18n`, it swaps out handlebars-like `{{message.example}}` for the `message.example` property in the language yaml file.

Do you think this has legs?

```javascript
import glob from 'glob'
import RootsUtil from 'roots-util'
import path from 'path'
import yaml from 'read-yaml'
import _ from '../assets/js/modules/underscore'

export default function(options) {

  return class I18n {
    constructor(roots) {
      this.category = 'views'
      this.util = new RootsUtil(roots)
    }

    fs() {
      return {
        extract: true,
        detect: file => this.util.with_extension(file, ['jade'])
      }
    }

    compile_hooks() {
      return { // TODO use async methods and return Promise
        write: ({roots, file_options, content}) =>
          glob.sync(path.join(roots.root, 'i18n/*'))
          .map(langFile => [
            content.replace(/\{\{(\S+)\}\}/g, (match, capture) =>
              _.getPath(yaml.sync(langFile), capture)
            ),
            langFile
          ]).map(([content, langFile]) => {
            const p = file_options._path,
                  dir = path.dirname(p),
                  ext = path.extname(p),
                  name = path.basename(p, ext),
                  lang = path.basename(langFile, path.extname(langFile))

            return {
              content,
              path: path.join('.', dir, `${name}.${lang}${ext}`),
              extension: `${lang}${ext}`
            }
          })
      }
    }
  }
}
```

**Comment by Leeds-eBooks** [comment]
@jenius With a few tweaks, this is working well for me, but I still haven't been able to make this work with `roots-records`. Looking at that extension's source code, it appears to be rendering single view templates "outside" the roots compilation flow, if that makes sense. See [this function](https://github.com/carrot/roots-records/blob/master/lib/index.coffee#L157).

I think this means that there's no way, _within_ the roots flow, to grab the contents of those compiled views and modify them. I could do some funky command line scripting after the compile step – at this stage, is that the only solution, or can you think of another trick?

**Comment by Leeds-eBooks** [comment]
Just in case anyone comes across this that is looking for i18n support in roots, I have actually solved the problem of `roots-records` single-view templates now. I will put my module up as an npm package at some point soon.

**Comment by jenius** [comment]
Yeah absolutely. Could you send it to me before publish? Would love to review!

**Comment by Leeds-eBooks** [comment]
@jenius Will do. It is pretty much the definition of hacky, but it works well for my purposes so I think it might help others too. Obviously if (when?) a better solution comes around, that would instantly take precedence. I'll be in touch soon.

**Comment by Leeds-eBooks** [comment]
@jenius https://github.com/Leeds-eBooks/roots-i18n

**Comment by jenius** [comment]
@Leeds-eBooks wow, this is a really impressive piece of work. nice job! That being said, the code is honestly boggling my mind. I'm having a really hard time understanding what you're doing here. Is there any way you could try to clarify the code a little? Or even a chance we could jump on a call or something and you could walk me through it?

**Comment by Leeds-eBooks** [comment]
Haha you're right. I can't do a call tonight but I will comment the crap out of it and hopefully that will help, and if not we could chat later in the week. Thanks for taking a look so quickly!

**Comment by jenius** [comment]
No problem, and thank you for making it! Let me know when you have updated.

**Comment by Leeds-eBooks** [comment]
Ok let me know if it makes any more sense now: https://github.com/Leeds-eBooks/roots-i18n

**Comment by Leeds-eBooks** [comment]
Hey @jenius I've been asked about getting this up on `npm` here: https://github.com/Leeds-eBooks/roots-i18n/issues/1

Do you think I can go ahead and use the `roots-i18n` package name on `npm`?

**Comment by jenius** [comment]
Hey @Leeds-eBooks -- yeah, I'm really sorry for the holdup. I've been working part time and had only very little time for this kind of stuff. I just read through the plugin and it looks legit. There's certainly some Babel stuff in there that could be cleaned up, and having tests in place would make a **huge** difference, but if it's working and people are using it by all means you are welcome to put it up on npm!

**Comment by jenius** [comment]
If I have some time on my hands I will certainly contribute some of these changes too :grinning:

**Comment by Leeds-eBooks** [comment]
Thanks man, I'll get this up today. Yeah I don't know what to do about he Babel stuff, I don't have time to rewrite it without es6, and I don't think we can assume that everyone is using the latest Node.js.

I'll write up some tests when I have a bit more time!

**Comment by Leeds-eBooks** [comment]
FYI https://www.npmjs.com/package/roots-i18n

**Comment by samccone** [comment]
wow amazing stuff @Leeds-eBooks

**Comment by Leeds-eBooks** [comment]
Thanks! :blush:

It is a little hacky though so any suggestions on how this could be integrated better into the rivets flow would be very welcome.
