### ISSUE TITLE
RSS Feeds for Dynamic Content

### ISSUE THREAD

**Issue by zspecza** [jenius/roots#258]
I think Roots could definitely benefit from the generation of RSS feeds for dynamic content. Both Jekyll and Octopress do this, but not all of the static site generators for node offer this feature - so having it available in Roots would probably increase the adoption rate. I wouldn't know where to start with this, but I'm sure it'd be a challenge. I do know that we have all the tools we need in place for something like this. There are also plenty of modules for this on npm: https://npmjs.org/search?q=rss+generator

**Comment by IRus** [comment]
@jenius I think RSS should be included by default(like in wordpress for example). Today i found an blog(http://andyshora.com/) and this blog built with roots. I want get latest updates and start searching RSS. And this blog actually doesn't have RSS! It's ridiculous... RSS should be zero-config included by default.

**Comment by jenius** [comment]
I agree. I would love to have this feature, I just don't have time
personally to implement it right now. If you'd be willing to contribute I'd
be happy to work with you! Otherwise I am doing my best to make things
happen, promise.
