### ISSUE TITLE
Integrate with browser-sync

### ISSUE THREAD

**Issue by jenius** [jenius/roots#367]
This would theoretically allow us to strip all the live reload stuff out.

https://github.com/shakyShane/browser-sync/issues/30

**Comment by dbox** [comment]
+1

**Comment by dbox** [comment]
@hhsnopek Is this something in your wheelhouse? Was just using another project with browsersync and it's soo fast.

**Comment by jenius** [comment]
Still would like to make this happen. Eventually will look into it when I have time, promise!

**Comment by declandewet** [comment]
This will be on my radar when I start :)

**Comment by jepedo** [comment]
Integrating browsersync would be slick. +1 for this.

**Comment by jenius** [comment]
So browsersync has it's own server, which would mean dropping charge and causing a number of breaking changes. However, its server [accepts middleware](http://www.browsersync.io/docs/options/#option-server), so it appears as if we could make it behave exactly like charge by just importing charge's middleware.

I think this won't be super difficult. Going to take a stab at it soon!

**Comment by jenius** [comment]
So integration is moving along. The issue though is the same issue we have with our home-made reloading system, the dependency tree and compile pipeline.

Let me explain. When you reload browser-sync, you can pass it the name of a file or multiple files to reload. So for example if you detect that `foo.css` changed, you would pass browsersync something like `bs.reload('foo.css')` and it would do its thing with the injection etc. Now here's the issue. Let's say you make changes to a jade layout file. We would have detected a change to `layout.jade`. However, this needs to be changed in a number of ways. First, it needs to be translated to its output path, which in this case is nothing since the file is ignored. Then it needs to pull in all its dependencies, which we have no way of attaining. This means any other jade file that uses it as a layout.

So basically, we cannot use browsersync to its fullest speed until all roots-supported compilers also drop dependency trees, and we make another set of changes to roots that allows us to track and use these trees for reloads.

That being said, there are two things that can be done here. The first is to try to approximate a couple use cases in which we can in fact reload just a single file, and for any cases where we can't be sure, reload everything. This was what we did in the previous version of roots, and while it ensured quicker reloads for a small number of use cases (like a single html view being changed), it also produced a number of bugs for edge cases where dependency reloads were not triggered and the watcher would have to be restarted. In this version, at the moment we simply reload everything each time the site changes.

For now, I'm going to move ahead with the integration and simply set it to reload everything each time, as it already does. As improvements come down the line and eventually we can perhaps make use of dependency trees, we will be able to take advantage of a little more speed out of browsersync, which will be great. Until then, the functionality will be there waiting for us.

Further discussion of the "dependency tree" issue can be found here for those interested and following along! https://github.com/jenius/roots/issues/586

**Comment by calebeby** [comment]
How can BrowserSync be configured in Roots?

**Comment by calebeby** [comment]
I want the browsersync script in `head` instead of `body`:

```js
snippetOptions: {
  rule: {
    match: /<\/head>/i,
      fn: function (snippet, match) {
        return snippet + match;
      }
  }
}
```
from https://github.com/BrowserSync/browser-sync/issues/977#issuecomment-236443965

**Comment by jescalan** [comment]
@calebeby currently there isn't an option to configure browsersync, although if you'd like to make a pull request to add one you are welcome to, [the logic is here](https://github.com/jescalan/roots/blob/master/lib/local_server.coffee#L31). I'm not sure I understand the need to do this though, isn't this an issue with rails/turbolinks?

**Comment by calebeby** [comment]
Sure, I'll see if I can work on it this weekend.
Turbolinks can be used outside of rails, it is just a script that
intercepts links like spike-pushstate.

It does not play nice with browsersync because browsersync puts the script
in body instead of head

**Comment by jescalan** [comment]
@calebeby honestly it would probably be better to just use spike-pushstate. I can fix it to work with the latest version if you want.

**Comment by calebeby** [comment]
Can spike-pushstate work with roots?

**Comment by calebeby** [comment]
Even if `spike-pushstate` does work with `roots`, it is still a good idea to make browsersync configurable. Are you still interested in me working on this?

**Comment by jescalan** [comment]
@calebeby it will definitely not work with roots, but [this project](https://github.com/djeglin/cygnus-js) would!
