### ISSUE TITLE
All the things, modern workflow necessities

### ISSUE THREAD

**Issue by brian-mann** [jenius/roots#392]
Sam and I were chatting and I made him a list of all the modern workflow necessities I would look for when choosing roots.  He mentioned roots already does many of these items but may be lacking others. 

We're a SPA shop, and we have a massive amount of JS files and assets.  We're looking to dump Rails in favor of a purely front-end focused workflow that can be deployed statically.  But I don't want to give up any of the control I have with Rails.

Here's what I'm looking for:

**CSS/Images**
- [ ] Sprite Generation (Compass)
- [x] SASS Support
- [x] Fine grained control over CSS manifests (being able to concat multiple .scss files into separate manifests at will)
- [x] Control different manifest strategies for development vs production
- [x] CSS Source Maps
- [x] Minification

**Templating**
- [x] Automatically precompile ECO templates when they change
- [x] Set their file path as the key in the global JST object for easy reference

**Environments**
- [x] Automatically control and set environment variables for test / development / production

**Javascript**
- [x] Fine grain control over manifests (ability to control which js files get concat'd into which manifests)
- [x] Control different manifest strategies for development vs production
- [x] Source Maps
- [x] Minification
- [x] Obfuscation

**Development**
- [x] Watches for any file changes and regenerates the changed assets
- [x] LiveReload

**Testing**
- [ ] Easy way to serve and organize static json fixture files used in tests without having to use sinon.js to manually fake XHR requests
- [ ] Testem / Karma Runner support
- [ ] Mocha / Chai

**Deployment**
- [x] Hash Digest all assets (JS manifests, CSS manifests, images)
- [ ] Generate a manifest.json file which is a key/val of all assets and their digest version
- [x] Deployment to s3
- [ ] GZipping all assets
- [ ] Zipping up the deployed /dist source, timestamping it (allowing for easy rollbacks)
- [ ] Execute arbitrary commands after deployment (like sending Pusher a message)

**Comment by jenius** [comment]
Ok so sourcemaps have been implemented and are fully functional in the sourcemaps branch. This will be merged and shipped out tomorrow. Pending a bit more polish on the docs site and some small adjustments to the deployment script, we will be merging v3 and going public with it. All that being said, I'm going to close out this issue for now. Thanks so much for bringing all these things up!

If there are any other issues here you'd like to see that I missed for some reason, we should open a single issue to discuss that feature :grinning:
