### ISSUE TITLE
Heroku deployment error

### ISSUE THREAD

**Issue by danielbaars** [jenius/roots#555]
When I try to deploy to Heroku I get an error:

$ roots deploy ./ -to heroku
Please enter the following config details for heroku
Need help? see http://carrot.github.io/ship/heroku
✘ TypeError: Cannot call method 'map' of undefined

**Comment by ChadMartinson** [comment]
I am getting the same problem on a linux machine.

**Comment by jenius** [comment]
Exactly the same error that was posted here, and you are on `3.0.0` stable?

**Comment by ChadMartinson** [comment]
Yes, exactly the same problem and I am on 3.0.0-rc.11

**Comment by ChadMartinson** [comment]
ok sorry needs to be roots deploy -to heroku and it is working

**Comment by jenius** [comment]
:+1:
