### ISSUE TITLE
V3 creating overly long file paths for Windows

### ISSUE THREAD

**Issue by 1jerry** [jenius/roots#557]
The dependency chain in module _charge_ for using _lodash_ is creating file paths that cannot be copied or deleted in Windows.

**Problem:**  Package _charge_ has "lodash.assign" and "lodash.remove" as dependencies.  Each of those packages has mutilple "lodash..." package dependencies **to nine levels!**.  This might not be a problem in posix, but Windows has a limit to the number of file path characters.  Example directory that I cannot open in Windows:

> B:\VCS\temproots\node_modulesx\charge\node_modules\lodash.remove\node_modules\lodash.createcallback\node_modules\lodash._basecreatecallback\node_modules\lodash.bind\node_modules\lodash._createwrapper\node_modules\lodash._basecreatewrapper\node_modules\lodash._basecreate\node_modules\lodash._isnative

**Suggestion:**:  It seems that almost every aspect of _lodash_ is being used but right now they're all over the place.  It appears you already have the _whole_ lodash package as a first level requirement anyway.  Why not just have _charge_ require that?

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:
```
lodash.assign@3.0.0
├─┬ lodash._baseassign@3.0.1
│ ├── lodash._basecopy@3.0.0
│ └─┬ lodash.keys@3.0.3
│   ├── lodash.isarguments@3.0.0
│   ├── lodash.isarray@3.0.0
│   └── lodash.isnative@3.0.0
└─┬ lodash._createassigner@3.0.0
  ├── lodash._bindcallback@3.0.0
  └── lodash._isiterateecall@3.0.1
```
and
```
lodash.remove@3.0.0
└─┬ lodash._basecallback@3.2.0
  ├─┬ lodash._baseisequal@3.0.1
  │ ├── lodash.isarray@3.0.0
  │ └── lodash.istypedarray@3.0.0
  ├── lodash._bindcallback@3.0.0
  └─┬ lodash.keys@3.0.3
    ├── lodash.isarguments@3.0.0
    ├── lodash.isarray@3.0.0
    └── lodash.isnative@3.0.0
```

You can also cherry-pick modules from `lodash`, for example `require('lodash/array/chunk')`.
