### ISSUE TITLE
Possible to reference views in the after callback?

### ISSUE THREAD

**Issue by mauvm** [jenius/roots#583]
I'm adding some prev/next buttons to my blog posts, but when the views are compiled the next post will not be available in `site.views.posts` because the next one will be processed after the current one.

I figured I'd let the `after` compilation callback write the list of posts to a temp file, which I can then build the nav from on next compilation.

If there is an easier way, I'm all ears! If not, I'm wondering if it is possible to access `site.views.posts` from inside the `after` callback?

**Comment by jenius** [comment]
Ok so this has been resolved by adding capabilities to the dynamic content extension and shipped out. You can see docs for it [here](https://github.com/carrot/roots-dynamic-content/blob/master/docs/intro.md#exporting-dynamic-content-as-json). Whoo!

**Comment by thiagodebastos** [comment]
Jeez, I just realised I could have saved hours by writing out a specific json file for my portfolio directory. At the moment, because it does not reside in 'posts', where, honestly, I should just put it, it is not (with my limited js/jquery know-how) easily accessed. This is how I was able to drill down to get the portfolio titles:

``` js
// still needs some work, I need to ignore 'undefined' results
$(document).ready(function() {
	$.getJSON('/content.json', function(data) {
		$.each(data, function() {
			$.each(this, function(index) {
				console.log(this);
				$.each(this, function(index) {
					console.log(this.title);
				});
			});
		});
	});
});
```

at one point I was using this, until it decided to stop working. It started giving me the same first portfolio item twice. sigh

``` js
	$.getJSON("/content.json", function(json) {
		var myjson = json;
		var related = "";
		var i = 0;
		var $related = myjson.portfolio.items[i];
		while (i < myjson.portfolio.items.length) {
			related +=
				"<h3> Portfolio " + [i] + " at key [" + [i] + "]</h3>" +
				"<br> <strong>Title</strong>: " + $related.title +
				"<br> <strong>Description</strong>: " + $related.description +
				"<br> <strong>Category</strong>: " + $related.category +
				"<br> <strong>Url</strong>: " + $related._url +
				"<br> <strong>Tags</strong>: " + $related.tags + '<hr>';
			i++;
		}
		// console.log(related);
		document.getElementById("json").innerHTML = related;
	});
```

**Comment by thiagodebastos** [comment]
The only wall I have hit now is finding a way to use js variables from within Jade. I can't seem to find a clear answer anywhere. I want to store the json into a variable that I can use in Jade. Is that better/more efficient than just injecting with AJAX?

**Comment by joshrowley** [comment]
You should take a look at [roots-records](https://github.com/carrot/roots-records), an extension that allows you to do exactly that. It will load JSON data from a file for use in your jade views. There's also a [roots-yaml](https://github.com/carrot/roots-yaml) extension if you prefer that data structure format.
