### ISSUE TITLE
roots --env should not mutate NODE_ENV

### ISSUE THREAD

**Issue by samccone** [jenius/roots#598]
So we ran into an issue on our site that when running `roots compile --env=foo` --env mutated the NODE_ENV, which caused some unexpected things to happen where our NODE_ENV and --env did not line up.

Not saying that this is wrong, just maybe document the precedence between the arg flag and the env var.

**Comment by jenius** [comment]
That's fine with me, documenting it is a good idea. Yeah an explicitly passed flag trumps an env var, because I figured if you have gone to the trouble of running the command with that flag, it's probably your intent. Want to open this up on the roots docs repo instead?

**Comment by samccone** [comment]
For sure 😅
