### ISSUE TITLE
[v2] layouts not working

### ISSUE THREAD

**Issue by teichmaj** [jenius/roots#599]
I'm new to roots and liked it a lot so far. The only thing which bugs me is that I cannot get layouts working.

In app.coffee I define two layouts:
```
layouts:
  default: 'layout.jade'
  'privacy.jade': 'plain_layout.jade'
```

I added some console.log and I noticed that the overwrite of the default layout never happens.

https://github.com/jenius/roots/blob/master/lib/extensions/layouts.coffee#L71
```
# if there's a custom override, use that instead
layout = roots.project.layouts[key] for key of roots.project.layouts if key is rel_file
```

However, the compile js version of that file on my local machine reads:
```
// Generated by CoffeeScript 1.7.0
if (key === rel_file) {
  for (key in roots.project.layouts) {
    layout = roots.project.layouts[key];
  }
}
```
and if I'm not mistaken this if condition is never true as key is always undefined, and therefore the layout overwrite never occurs.

**Comment by jenius** [comment]
You're right, this is a known bug in roots v2, I'm really sorry. The current version on master is very out of date, we have been working for more than a year on the next version of roots, which can be found [here](https://github.com/jenius/roots/tree/v3). This version is significantly more stable and powerful, and is looking at a public release this or next week, so we have not been fixing up v2 bugs as frequently.

If you want to fix this bug, I would definitely accept a pull request for it, but we have been focusing all our energy on getting v3 released and haven't had time to patch up things like this recently.

**Comment by jenius** [comment]
v3 has been released as stable, going to close this one out. Still would accept a PR to backfix it, but we're not focused on developing v2 anymore unfortunately

**Comment by teichmaj** [comment]
Good job for releasing v3! I will give it a try when I have some time. Unfortunately, I moved away from roots to grunt for the project I am currently working on. So I haven't tried to fix it up and I'm not very optimistic I will find the time any time soon :(

**Comment by jenius** [comment]
Haha we've been doing some work transitioning people from grunt to roots v3 recently. Cut down a 100+ line config file to three lines, no joke :grinning:
