### ISSUE TITLE
Axis-Css@0.0.3 deprecated

### ISSUE THREAD

**Issue by scarnago** [jenius/roots#602]
This is the only WARN I get when install roots npm WARN deprecated axis-css@0.0.3: package located at 'axis' rather than 'axis-css
Just to let you know

**Comment by jenius** [comment]
Yup, is is deprecated. The main install of roots is also severely out of date, and we are releasing a new version of roots this week.You can check it out for now on the `v3` branch. Sorry for the awkward transition period!

**Comment by scarnago** [comment]
I have to uninstall roots and install this new v3? How I do that?

**Comment by jenius** [comment]
`npm i roots@pre -g`

If you are new to node and roots I would recommend just waiting until we release the new version stable, which will happen before the end of this week. it will come with clear instructions, documentation, tutorials, and videos.
