### ISSUE TITLE
postinstall message about analytics gets buried

### ISSUE THREAD

**Issue by sperand-io** [jenius/roots#605]
Congrats on Roots 3!

I love what you guys are doing with Keen around the anonymous CLI/API analytics, and especially love the sentiment around making it transparent, obvious, and easy to disable with the postinstall message. 

However, I've noticed the postinstall script gets buried by the final `npm WARN`s and dep tree. I have absolutely nothing helpful to add here, as I couldn't find anything from npm/google on how to avoid that. Thought it was worth raising in case you might have any ideas, but if this is something you are already aware of and there's no known fix, please close and carry on — with many thanks for all of your great work.

![](https://cloudup.com/cAppG16An9n+)

**Comment by jenius** [comment]
Hey @sperand-io -- thanks for the heads up! It seems like actually this is an issue with npm and your local node install, I don't see any of those npm warnings, and they are not normal. Usually the postinstall is the final message that appears after installation.

Thanks for the notice though, and the kind words about roots! I'm going to close this out as it's not an issue with our code, and not one that we can fix, but will keep an eye on it for the future :grinning: Of course let us know if there are any other things we can help with or things you notice.
