### ISSUE TITLE
hiding directory from public path

### ISSUE THREAD

**Issue by pruett** [jenius/roots#610]
killer release @jenius! apologies if this has already been addressed. 

im looking to achieve a simple blog structure with [dynamic content](https://github.com/carrot/roots-dynamic-content). i threw the posts in a folder called `logs` and was looking to hide that directory from the url, so for example, instead of `logs/first-post.html`, it would resolve at `/first-post.html`

i played around with [pathologist](https://github.com/carrot/pathologist-middleware) without any success and wondered what the preferred method of execution would be for this use case.

at the moment, im simply ditching the `logs` directory, and putting the entries on the root directory. i'm accessing the entries with a `each log in site["."]` iteration loop which seems to work.

is that what i should be sticking with you think?

**Comment by jenius** [comment]
Ok so two ways I can see this being worked out:

1. We're thinking of adding to dynamic content such that you can pass a globstar to it if you want and it will just run that directory. This will probably be added next week and would enable this behavior.

2. If we added [placeholders](https://docs.netlify.com/redirects/#placeholders) to charge, it would enable you to rewrite correctly. You can do this with netlify already as shown above, if you want.

**Comment by pruett** [comment]
very cool, thanks brother

**Comment by jenius** [comment]
You don't have to close if you don't want. I'll update here when there's a good way to solve this either way!

**Comment by pruett** [comment]
i just didn't want to clutter up core roots with this issue. a cross reference a dynamic content issue of the same name makes more sense to me.

**Comment by jenius** [comment]
Cool, feel free to open one up there then if you want!
