### ISSUE TITLE
Charge server crashing without errors while running 'roots watch'

### ISSUE THREAD

**Issue by dustinrjo** [jenius/roots#612]
I'm loving Roots and its convention over configuration, so thanks for that!

Having some issues though...

While running `roots watch` I get *localhost:1111* going and on each save it re-compiles.  Great, fantastic really, but after 3-5 times of doing the re-compile the compile completes without any error in the console and the public folder has all the files but *localhost:1111* goes dead and does not serve any of the files.

I am getting absolutely no logging out of Roots other than "compiling....**done!**"

I read the documentation and found that you can't set the Charge "log" variable and that you are supposed to use "debug" as an option but I'm not getting anything out of that.

Here is my app.coffee

    axis         = require 'axis'
    rupture      = require 'rupture'
    autoprefixer = require 'autoprefixer-stylus'
    js_pipeline  = require 'js-pipeline'
    css_pipeline = require 'css-pipeline'
    jeet = require 'jeet'

    module.exports =
      ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']

      extensions: [
        js_pipeline(files: 'assets/js/*.coffee'),
        css_pipeline(files: 'assets/css/*.styl')
      ]

      open_browser: false

      debug: true

      stylus:
        use: [axis(), rupture(), autoprefixer(), jeet()]
        sourcemap: true

      'coffee-script':
        sourcemap: true

      jade:
        pretty: true

      server:
        clean_urls: true

I'm on OSX Mavericks if it makes a difference and can't upgrade without breaking a legacy project.

This is a very clean install of Roots on a new project started just a couple days ago.

Any ideas how I can help figure out what is wrong?  Anyone else getting this kind of behavior?

**Comment by jenius** [comment]
Hey @dustinrjo -- thanks for the well-reported issue. This is weird, never seen an error like this before. In order to figure out the cause I'd need to be able to replicate it on my end and investigate. Is there any way you can zip up the project (sans node modules) and send it to me, or drop it here?

**Comment by dustinrjo** [comment]
Sure, I will rip out a few of the private bits, images etc and make sure the error persists then zip it and post it to you

**Comment by dustinrjo** [comment]
So I duplicated the project and replaced all the text content with Doge ipsum and it stopped happening.  

Something about my site content must be breaking it because changing the content significantly fixes it.

That doesn't make much sense at all to me because Roots compiles it fine and the Charge server should be just serving those static files.  If I'm able to reproduce it more consistently I will post again but for now I won't drag you into this strange bug.  

It is still persisting on me though every 5-10 compiles with the actual site content I want to use but I will close this for now.  If nothing else it was a fun opportunity to look under the hood of how you built this sweet tool.  If you do have any tips for debugging though please let me know or add that to the documentation.  Setting the debug option literally does nothing for me, at least that I'm seeing.

Thanks!

**Comment by jenius** [comment]
Huh, very strange. If you can find anything else or a way to reproduce, let me know for sure, happy to try to help out!
