### ISSUE TITLE
Use Sass

### ISSUE THREAD

**Issue by peduarte** [jenius/roots#614]
Hey there,

I'm sure you've been asked this before but I cannot find anything related.

Due to some project restrictions I need to use Sass on a project.

Looking at app.coffee, I have no idea how to do that.
I understand that sass runs on ruby and that I'd need libsass in order for it to work with node.

Could you please enlighten me on whats the best direction?

Thanks a lot

**Comment by slang800** [comment]
accord supports sass, so you just need to do `npm install libsass --save` & you'll be gtg.

**Comment by peduarte** [comment]
Thanks.

What about on app.coffee?
What do I need to modify on there?
Currently it has css pipeline in the extension array, and some stylus configuration.

**Comment by slang800** [comment]
Nope, you shouldn't need to do anything to your app.coffee... accord will just see that node-sass is installed and it'll use it on all the sass files it finds. All that config is handled for you in accord: https://github.com/jenius/accord/blob/master/lib/adapters/scss.coffee

**Comment by peduarte** [comment]
Got an error but we figured it out. Need to update the version of Accord in root's package.json to the latest one :)

Pull request by @aendrew on the way...

**Comment by aendrew** [comment]
Just to document this fully: using Roots with Sass in the latest version yields "TypeError: Object.keys called on non-object". Updating Accord to 0.15.x fixes this.

**Comment by jenius** [comment]
Thanks guys, sorry about that. Breaking change in the latest node-sass api. I'll get this merged and shipped out first thing tomorrow.
