### ISSUE TITLE
Live Reload script not injected into single post

### ISSUE THREAD

**Issue by thiagodebastos** [jenius/roots#618]
## Context

Live reload does not work on any of my single posts. Before I go on, here is my current project structure:

### Current structure:
```
mysite/
|  posts/
|  |  creations/
|  |    first-creation.jade
|  |    second-creation.jade
|  |  thoughts/
|  |    first-thought.jade
|  |    second-thought.jade
|  views/
|  |  index.jade
|  |  layout.jade
|  |  single-thought-layout.jade
```
### single-thought-layout.jade
``` jade
head
  title= _path.match(/[-a-zA-Z0-9@:%_\+]{4,256}(?=\.[html|php])/g)

  != css('/')

body

  h2= post.title
  
  block content

  a(href='/') &laquo; back to index
  != js('/')
```
- - -

## My fix
The only way it works is if I manually add the roots script to `single-thought-layout.jade`

``` jade
script(src='/__roots__/main.js').
  var __livereload = true
```
I found that snippet of js by surfing through the rendered source code. For some reason Roots is not injecting this code into single posts. Any idea why?
I'm also a bit baffled, do I put all my pages into 'views'? I have googled far and wide and can't seem to find anything related to Jade directory structures.

**Comment by jenius** [comment]
You are missing a `html` element in your layout. If you add this it will inject correctly. It looks for that element in order to anchor onto, as it's necessary for any valid html page.

**Comment by jenius** [comment]
As for where to put your pages, you can put them wherever you want, and roots will compile them just fine :grinning:

**Comment by thiagodebastos** [comment]
Wow. I thought that was it and wrote it off because it didn't work. I looked back and realised that I had forgotten to indent everything after the doctype. I can't believe how easy it is to get carried away with `fixes` when the issue comes down to a brainmelt. Thanks!

**Comment by jenius** [comment]
Haha I entirely understand where you are coming from there. It happens. I really appreciate the amount of time you put into trying to debug this and writing up such a clear issue. Let us know if there's any other issues you're running into, happy to help!
