### ISSUE TITLE
can I use Less in roots? and how?

### ISSUE THREAD

**Issue by ilife5** [jenius/roots#620]

**Comment by declandewet** [comment]
Yes, you can. Just change the extension of your stylesheets from whatever they are (`file.css`, `file.styl`, `file.scss`, etc) to `file.less`, and then `npm install less --save-dev`

**Comment by ilife5** [comment]
@declandewet  it doesn`t work

roots output file.less to public

**Comment by declandewet** [comment]
Strange... It *should* work. Try adding `less` to your regular `dependencies` in `package.json`. 

Roots uses [Accord](jenius/accord) under the hood for file compilation, and all that is required is having the necessary compiler for your transpiled language installed and the correct file extension. The tests for it pass, but I'm going to try reproduce this and get back to you.

**Comment by declandewet** [comment]
It seems to work just fine:

![](http://cl.ly/image/0y3W0R0W3v3A)

What version of Roots are you using? Could you provide more information?

**Comment by jenius** [comment]
Yup should be working exactly as @declandewet described. Thanks for handling this issue Declan :grinning:

**Comment by ilife5** [comment]
@declandewet thanks.It worked. 
I have tested under 3.0.0 and 3.0.1。
