### ISSUE TITLE
support for the Sass indented syntax

### ISSUE THREAD

**Issue by javaporter** [jenius/roots#621]
The SCSS syntax of Sass can be used quite easily, but not the indented syntax. In node-sass there is an option that can be set: `indentedSyntax: true`, but I couldn't figure out how to make that work with my roots project (might be a user error).

**Comment by jenius** [comment]
Oh you can just add this line to your `app.coffee` file:

```coffee
module.exports =

  scss:
    indentendSyntax: true
```

Now that this works though we should probably ass `sass` as an extension on accord too :grinning:

**Comment by javaporter** [comment]
Hmm, kind of works. So, you still have to name your file with a `.scss` extension, which confuses your syntax highlighting. There are workarounds to that issue, but it's not ideal. I have something mocked up here if someone wants to play with it. This was my first crack at a roots project, it includes some things like contentful integration and yaml front matter too. https://github.com/javaporter/roots

**Comment by jenius** [comment]
Yeah definitely, I'll look into enabling the sass syntax as well. This
particular compiler is unique in the fact that you use the same compiler
for two different languages with different extensions, so I'll have to
tinker around a bit to make sure it's smooth.
