### ISSUE TITLE
Jade compile limit

### ISSUE THREAD

**Issue by thiagodebastos** [jenius/roots#622]
After a certain amount of includes, Roots will stop compiling after around ~30 includes (I maxed at 32 includes)

```jade
//- styleguide.jade
include /_patterns/atoms/lists/ordered
```

```jade
//- orderered.jade
.text
	ol
		li This is a list item in an ordered list
		li
			| An ordered list is a list in which the sequence of items is important. An ordered list does not necessarily contain sequence characters.
		li
			| Lists can be nested inside of each other
			ol
				li This is a nested list item
				li This is another nested list item in an ordered list
		li This is the last list item
```

![screen shot 2015-03-15 at 21 01 39](https://cloud.githubusercontent.com/assets/6151341/6658097/8965b99a-cb56-11e4-80a9-715c77e2a35b.png)
_open tag is where it gets cut off_

- - - 
This does not seem to be an issue with Jade as compiling with Jade CLI works as expected.

**Comment by hhsnopek** [comment]
Does it still not work if you compile via command line (with jade)?

**Comment by thiagodebastos** [comment]
It works fine with Jade CLI, I did mention that, I'll move the text around as you may have missed where I said it :)

**Comment by jenius** [comment]
This is a very strange issue. I honestly have no idea why it's happening. Is there anyone that can dig a little deeper? I don't really have the capacity to at the moment...

**Comment by thiagodebastos** [comment]
Hmm it seems that this happens way before 30 includes, I can't get past 8 includes in on atoms-2.jade

```jade
//- atomic-mixins.jade
mixin atom-meta-head
	head
		title #{locals.site.title}
		meta(charset='UTF-8')
		meta(name='viewport', content='width=device-width, initial-scale=1"')
		meta(name='description', content='description of your site')
		meta(name='author', content= "author of the site")
		!= css('/')

```


```jade 
//- styleguide-layout.jade
include /_patterns/templates/_atomic-mixins.jade

doctype html
html.htmlClass(class='{{ }}' lang='en')

	+atom-meta-head
	
	block content

	script(src='/assets/js/vendor/jquery-2.1.3.min.js')
	!= js('/')
```


```jade
//- atoms2.jade
extends styleguide-layout
block content
	#sg-patterns
		#atoms-select-menu
			h2.sg-pattern-head Select Menu
			.sg-pattern-body
				include /_patterns/atoms/forms/select-menu
		
		#atoms-checkbox
			h2.sg-pattern-head Check Box
			.sg-pattern-body
				include /_patterns/atoms/forms/checkbox
		
		#atoms-radio-buttons
			h2.sg-pattern-head Radio Buttons
			.sg-pattern-body
				include /_patterns/atoms/forms/radio-buttons
		
		#atoms-html5-inputs
			h2.sg-pattern-head HTML5 Inputs
			.sg-pattern-body
				include /_patterns/atoms/forms/html5-inputs
		
		#atoms-buttons
			h2.sg-pattern-head Buttons
			.sg-pattern-body
				include /_patterns/atoms/buttons/buttons
		
		#atoms-table
			h2.sg-pattern-head Table
			.sg-pattern-body
				include /_patterns/atoms/tables/table
		
		#atoms-video
			h2.sg-pattern-head Video
			.sg-pattern-body
				include /_patterns/atoms/media/_video
		
		#atoms-audio
			h2.sg-pattern-head Audio
			.sg-pattern-body
				include /_patterns/atoms/media/_audio

```


Here is my project: https://github.com/thiagodebastos/atomic-roots

**Comment by hhsnopek** [comment]
Everything compiles for me, I had an issue using roots 3.0.0 rather than 3.0.2 - are you up to date on roots? 

![ordered list](https://cldup.com/oyklm4fUN8.png)

**Comment by thiagodebastos** [comment]
Hmm things just got weirder. In both Chrome and Firefox I get this:
![screenshot-nocompile-roots](https://cloud.githubusercontent.com/assets/6151341/6677400/84f58b16-cc27-11e4-9949-648c7abfc08d.png)

Apologies for my lack of better issue-description, I am exhausted!

**Comment by hhsnopek** [comment]
Have you tried a fresh install of roots? Maybe commit your changes, delete the project and reclone it down?



--
Henry Snopek

**Comment by thiagodebastos** [comment]
I did as you suggested and it worked. Not sure what went wrong there. I suppose we can close this?

**Comment by jenius** [comment]
Yeah very strange. Thanks for handling this one @hhsnopek!
