### ISSUE TITLE
Templates with "trailing extensions" are compiled

### ISSUE THREAD

**Issue by 4d47** [jenius/roots#626]
I'm just starting with Roots, using version `3.0.1`.

File "trailing extensions" is ignored when matching and files are compiled. eg.:
````
assets/css/a.styl.orig -> public/css/a.css
views/a.jade.foo.bar -> public/a.html
```

Note that backup files (eg. app.coffee~) are not matched and copied as-is to the final build.
(Understandable but ignoring them would be nice enhancement)

This is problematic as it make `roots compile` fail when the file contains non-template data.
For example when using Vim [swap-files](http://vimdoc.sourceforge.net/htmldoc/recover.html#swap-file).

```sh
compiling... Warning: missing space before text for line 2 of jade file ".../views/.index.jade.swp"

compiling... ✘ Error: .../.app.coffee.swp:1:10: error: unexpected 
b0VIM 7.4��U'
    pretty: true  jade:    sourcemap: true  'coffee-script':    sourcemap: true    use: [axis(), rupture(), autoprefixer()]  stylus:  ]    css_pipeline(files: 'assets/css/*.styl')    js_pipeline(files: 'assets/js/*.coffee'),  extensions: [  ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']module.exports =css_pipeline = require 'css-pipeline'js_pipeline  = require 'js-pipeline'autoprefixer = require 'autoprefixer-stylus'rupture      = require 'rupture'axis         = require 'axis'
         ^
```

**Comment by hhsnopek** [comment]
A quick fix to to create an [ignore rule](http://roots.cx/docs/configuration) within your `app.coffee`, as well we have support for [multi-pass](http://roots.cx/docs/multipass) because if can be useful to use.

**Comment by jenius** [comment]
Yup exactly what I would have said. If you have files you do not want to be
compiled you should ignore them to avoid issues. Roots uses extensions in a
particular way to make compilation simple for files that are actually
compiled. Uncompiled files should either be ignored or deleted and you can
use git to keep track of versioning.

**Comment by 4d47** [comment]
Thanks for the responses, so I got bitten by that multipass file extension logic.

But why compiling "example.jade.foo.bar" to "example.html" since foo and bar do not match a compiled extension ? Wouldnt it make more sense to avoid compiling unless all extensions match a language ?

**Comment by jenius** [comment]
Nope, this logic is quite sound for all normal use cases. I don't think you got bitten by this logic really, it was just that you were using a strange convention for un-compiled or backup files and this was one of the side effects. We spent a bunch of time thinking about each part of the extension compilation logic and making sure that it matches any applicable use case in which you intend to use the compiled file as output.

You can read more about the logic and why we made the choices we did [here, in the docs](http://roots.cx/docs/multipass). If you do have a use case in which you are trying to compile a file in a particular manner for use in the compiled site and this logic isn't allowing you to do so, detail it here and we can re-open and take another look!

**Comment by 4d47** [comment]
Was with Vim default settings, no strange conventions or anything.

**Comment by jenius** [comment]
Huh. We have a bunch of people who use roots with vim and haven't run into major issues like this. Maybe @samccone or @joshrowley would be able to advise?
