### ISSUE TITLE
Any way to preserve JS or Coffee comment blocks during minification?

### ISSUE THREAD

**Issue by dustinrjo** [jenius/roots#628]
Using all my other build tools and compilers using `@preserve` or `@license` works.

I like to include easter eggs in my code that are not minified like this for example:

![screenshot 2015-03-31 21 41 25](https://cloud.githubusercontent.com/assets/5560990/6934797/4d557238-d7ef-11e4-929d-bcdae2601135.png)

I haven't found any documentation on how this is treated, but here is my production config file.

    axis         = require 'axis'
    rupture      = require 'rupture'
    autoprefixer = require 'autoprefixer-stylus'
    js_pipeline  = require 'js-pipeline'
    css_pipeline = require 'css-pipeline'
    jeet = require 'jeet'

    module.exports =
      ignores: ['readme.md', '**/layout.*', '**/_*', '.gitignore', 'ship.*conf']

      extensions: [
        js_pipeline(files: 'assets/js/*.coffee', out: 'js/main.js', minify: true, hash: false),
        css_pipeline(files: 'assets/css/*.styl', out: 'css/style.css', minify: true, hash: false)
      ]

      stylus:
        use: [axis(), rupture(), autoprefixer(), jeet()]

      server:
        clean_urls: true
        gzip: true

I'm sure you can understand the *extreme* importance of this kind of functionality.  Thanks!

**Comment by jenius** [comment]
Haha of course, just add this line:

```
jade:
  pretty: true
```

and your comments will live on with vibrant life :sparkles:

**Comment by dustinrjo** [comment]
If my comments were in Jade I would agree.  Having tested this, I'm seeing that that does not have any effect on CoffeeScript which is where I want to preserve the comments.

An example from a Rails project I worked on:

http://www.badassembly.com/assets/application-e8dd98f992baf47a9cf46cc9e2674e5a.js

The code itself is all minified, but comments needed for attribution are preserved.

Is there a way to configure *this* in Roots?

**Comment by jenius** [comment]
Hahah oh I'm sorry! Totally blew it. This is a question about [the js pipeline](https://github.com/carrot/roots-js-pipeline) then? How are you minifying js?

**Comment by dustinrjo** [comment]
Indeed that sounds correct.

Currently I'm using the basic out of the box config here:

    js_pipeline(files: 'assets/js/*.coffee', out: 'js/main.js', minify: true, hash: false)

Somehow I need to pass a flag to UglifyJS that seems to be under the hood of the js_pipeline's minifications that tells it to `--comments`

I found this here: https://github.com/mishoo/UglifyJS2#keeping-copyright-notices-or-other-comments

I'm not so sure how to set those options in the roots config for the js_pipeline based on the documentation.  

I'll dig through the code now to see if I can figure it out, but hopefully that paints a picture of what I'm trying to solve if you have any ideas.

**Comment by jenius** [comment]
I'll get this added to js pipeline as long as uglify's JS API supports this option. One moment...

**Comment by jenius** [comment]
K, just published, it should now preserve comments. Whoo! :tada: Just update to the latest version of js pipeline and you should be set.

**Comment by dustinrjo** [comment]
Hi Jeff,  I finally got a chance to test this thoroughly and I could be doing something wrong, but I've tried a lot of different things and I'm not certain your implementation works when `minify: true`

I've got the latest release from you and even tried the exact code from the test.coffee you wrote.

Again, my production config is this:

`js_pipeline(files: 'assets/js/*.coffee', out: 'js/main.js', minify: true, hash: false)`

It works when minify is false, but that is not the challenge here, the challenge is to enable the `--comments` flag in Uglify to only preserve comments that are `@preserve` or `@required`

I tried this:

`js_pipeline(files: 'assets/js/*.coffee', out: 'js/main.js', minify: true, hash: false, comments: true)`

and this

`js_pipeline(files: 'assets/js/*.coffee', out: 'js/main.js', minify: true, hash: false, opts: {comments: true})`

But it seemed like the code change you made would just enable the comments flag by default without any config needed, though I don't know exactly how it does that.

Thanks for you swift responses!

**Comment by jenius** [comment]
Yeah I figured having it on by default was fine. I don't see many situations where someone would write `@preserve` and expect the comment to be gone haha.

The change was super simple, right here: https://github.com/carrot/roots-js-pipeline/commit/99f2be5be0097a9243aea7974e2e36fd4d605307

I added a test as well and verified that it was working, although perhaps something wasn't quite right? Feel free to take a look at the js pipeline code and open an issue there if you are still having trouble. It's pretty simple code, if you are feeling ambitious you could pull it down and try to open a PR to fix it too!
