### ISSUE TITLE
One more lifecycle hook specifically for before compilation but after locals have been set

### ISSUE THREAD

**Issue by declandewet** [jenius/roots#633]
Specifically referring to the `before` / `after` hook options in `app.coffee`.

`before` runs before any compilation, but also before any locals have been set via extensions.

`after` runs after compilation.

What if a user has the need to transform locals provided by extensions before compilation?

**Comment by jenius** [comment]
I feel like if you need to get that specific, this is what extensions are for...

**Comment by declandewet** [comment]
On the contrary, my use case is to simply combine two separate records from `roots-records`, which is far too simple to warrant a whole new extension.

When I say "combine", what I mean is if I have an array of `categories` and an array of `articles` that come from separate API endpoints, and I wish to now tack the `article`s that are linked to the UUID of the `baby` category into an array directly on the `baby` category.

I've tried using templating logic here, but for some reason some pages (like layout files and single view templates) do not get the roots-records locals. I've tried looking into what causes that and it makes no sense. But having this kind of functionality would have saved me having to figure out how to get both APIs how I want them (which is by using `request` in `app.coffee`, it's ugly - unnecessary http requests etc)

**Comment by jenius** [comment]
Hmm ok. When I have had a use case like this in the past I ended up making a small API wrapper that would do the syncing to other APIs and combining logic etc to make it more straightforward, but if you want to do it all in roots it should be feasible I suppose.

So you are basically looking for a roots-native hook in order to hack an extension's functionality. Is there any reason you don't want to have the hook added to roots-records itself?

**Comment by declandewet** [comment]
I did suggest it over in the `roots-records` repo, but I got thinking and this would also work and might be better in fact, because it doesn't tie too closely to any single extension and could be used in more ways

**Comment by jenius** [comment]
I still don't see this happening. You can just drop a tiny extension directly into your `app.coffee` file and use the extension hooks, or write an extension that's just a couple lines and load it. `app.coffee` is only for the basics, not intended to be a massive and complex config file. A lot of the draw of roots for us in fact is that `app.coffee` is usually simple and clean. Starting to add in complex hooks like this needed for more advanced hacking I feel is a step in the wrong direction.

I'd still recommend making a tiny extension and loading it in here, as it gives you the hook control you need without as much of an extra mess.
