### ISSUE TITLE
.htaccess extension

### ISSUE THREAD

**Issue by dbox** [jenius/roots#634]
Apologies if this is covered somewhere else, or a major faux-pas to the mindset behind roots.

I love the instant deploy to netlify (and all the optimizations that they do server side) but we still have a lot of clients that need to be an apache server ala Mediatemple.

Would you have any interest (or does it already and i'm not seeing it) in having roots spitting out the correct .htaccess for the clean urls?

**Comment by kylemac** [comment]
hey @dbox we've got a roots extension called [roots-netlify](https://github.com/carrot/roots-netlify) that exposes an easy-to-use interface to [netlify's redirect rules](https://docs.netlify.com/redirects/). this plugin will compile the appropriate `_redirects` file in your root path. note, this extension isn't 100% necessary, you could write out a `_redirects` file in your project -- we just like having it in our `app.coffee` where all our other configuration is. further, josh lays it out a little in the readme of roots-netlify

> It's also a common roots convention to start files with an _ to ignore them during compilation. Since Netlify would normally be configured with a _headers and _redirects file, using this extension allows you keep that nice clean convention throughout the whole project.

**Comment by kylemac** [comment]
oh, I see that doesn't exactly answer your question. for .htaccess - if you simply put a `.htaccess` file in your root-dir, roots will copy it over to `public/.htaccess` at which time you can point your apache configuration to that.

**Comment by dbox** [comment]
Thanks @kylemac. Yeah, sorry I wasn't clear. Basically I'm wanting roots to auto-magically generate the mod-rewrite rules to the .htaccess file. Basically the same thing it's doing for netlify: `mysite.com/about.html` -> `mysite.com/about/`

Obviously it can be done manually but that's the beauty of roots. Taking away all the dirty work. :smile: 

If this is out of scope of roots, totally understandable, but it'd be super handy.

**Comment by declandewet** [comment]
I think this might actually be possible using an extension, but it would be a little complicated. Essentially, this extension would have to:

1. Know what files are going to be compiled
2. Even if their compilation is the responsibility of another extension
3. While maintaining a buffer string that will eventually get compiled after everything compiles

The buffer string would eventually get compiled to the `.htaccess` file that maps the compiled URL to a rewrite rule.

The really tricky part is getting the extension to know what files are compiled or not. This is easy for standard Roots static or compiled files - simply inspect the templating engine view and check if it has a partial or not - but pages made through `roots-records` will be a hell of a lot trickier to detect...

Perhaps having it fully-automatic might mean it will be a little over-engineered. Perhaps being explicit and providing a glob match for this kind of thing would be easier - but therein again lies the problem of matching against views generated by other extensions...

**Comment by eteubert** [comment]
I was just stumbling over the same issue, that `/about.html` is accessible but `/about/` is not. I didn't realize it's a netlify feature.

Suggestion: Add an option that renders `/about/index.html` instead of `/about.html`. Then accessing `/about/` works in every environment, even locally.

**Comment by declandewet** [comment]
I think Jeff and I once spoke about supporting canonical URLs (like you are describing here) and there was an issue that prevented them from making their way into Roots. However this was before V3 so I think we could explore the idea again as I am also interested.

For now, you can do the same thing with this in your `app.coffee`:

```coffeescript
server:
  clean_urls: true
  # and other things like:
  # gzip: true
```

But in production you will have to use [Charge](https://github.com/carrot/charge) to serve your site.

**Comment by kylemac** [comment]
yeah, what declan said -- we use [charge](https://github.com/carrot/charge) (which is built into roots and is what is serving your site when you run `roots watch`) for our local development. it has all the features you'd want from a web-server so you don't have to install apache locally or something crazy like that. then in our `app.production.coffee` we usually default to netlify's clean url rewrite. if we were deploying to an apache server, we would just write a basic `.htaccess` into our project and use that. 

to see what declan shared in more context, here's the `app.coffee` file for <http://roots.cx> which is hosted on netlify - https://github.com/carrot/roots-www/blob/master/app.coffee#L26-L27

**Comment by dbox** [comment]
@kylemac but wouldn't it be *awesome* if roots (or an extension) automagically wrote that `.htacess` file for you? :smile:

**Comment by joshrowley** [comment]
@dbox That's a perfect use case for roots extensions. There's a [roots-netlify](https://github.com/carrot/roots-netlify) extension that writes config files for a static hosting platform called [Netlify](https://www.netlify.com/). It's a good starting point for figuring out how to write an extension for writing an `.htaccess` file.

**Comment by dbox** [comment]
Thanks @joshrowley. Might be a little over my head at the moment, but hopefully someone can take it on.

**Comment by maniqui** [comment]
I might be missing something, but the code for serving `/about.html` (when accessing `/about`) using `.htaccess` is just the following:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^\.]+)$ $1.html [NC,L]
```

So, @dbox , this means that you don't need to "auto-magically generate the mod-rewrite rules to the .htaccess file", because you can do that with just one simple rule for every URL (instead of one rule for each URL).

**Comment by dbox** [comment]
Well awesome. Didnt know you could do that. Thanks!
