### ISSUE TITLE
code with pure js instead of coffeescript?

### ISSUE THREAD

**Issue by adampotocki** [jenius/roots#637]
Hi, sorry if i'm not seeing this in the docs/closed issues but is there a way to code roots with pure js instead of coffeescript?  

Much thanks in advance :)

**Comment by adampotocki** [comment]
almost forgot to ask, is there support for babeljs or es6?

**Comment by hhsnopek** [comment]
Hey @adampotocki you can convert all of your scripts into pure javascript with the expection of `app.coffee` (if i'm not mistaken). If you want to use any other languages within roots checkout [accord](//github.com/jenius/accord). Babel is supported in accord so you can use it!

**Comment by hhsnopek** [comment]
Adding a little clarity, roots uses accord to compile everything. All you need to do is install the language you'd like to use via npm and roots will automatically pick it up and compile it for you :grinning:

**Comment by adampotocki** [comment]
now way :smile:! thank you!

**Comment by hhsnopek** [comment]
No problem, if you have any other questions let us know! :smile:

**Comment by christiansakai** [comment]
I tried to add `assets/js/main.js` and inside `main.js` I put `console.log("heyy");` but it doesn't work at all, am I missing something?

**Comment by jenius** [comment]
@christiansakai did you load the file on to your page in the html?

**Comment by christiansakai** [comment]
@jenius Yes I did, in fact, main.coffee is automatically converted to main.js am I right? the index.html's main.js is already there from the main.coffee

**Comment by jenius** [comment]
@christiansakai yes it is. You can check the `public` folder if you want to see the compiled files. Probably there was an issue with the path. Have you checked the console?
