### ISSUE TITLE
XML Sitemap Generator

### ISSUE THREAD

**Issue by Gioni06** [jenius/roots#638]
Hi, What would be a good starting point to build an extension for automatically generation of xml sitemaps ?

**Comment by jenius** [comment]
Hey there @Gioni06! Glad you are looking to get involved. Here are the docs for building extensions: http://roots.cx/docs/extensions

It's not the easiest thing ever, but they can be quite powerful, you can basically mod any part of roots in any way. To get started with this, I would probably create a pass through extension that takes stock of all the pages being processed, then passes them on to the processing without messing with them. When finished, it could do it's thing and generate the sitemap. Shouldn't be too tough once you get it going :grinning:

**Comment by Leeds-eBooks** [comment]
@Gioni06 Did you make a start on this? Thinking of starting myself but don't want to duplicate work!

**Comment by Gioni06** [comment]
@Leeds-eBooks No i didn't. I stopt working on this particular project. But please tell me when you start a project. I would definitely help you where possible.

**Comment by ngarland79** [comment]
This would be an excellent addition to roots. Manual sitemaps are no fun.

**Comment by jescalan** [comment]
@ngarland79 you should work on an extension that does this! happy to help if you need it 👍

**Comment by ngarland79** [comment]
Great, thank you! I will look into it as soon as I can.

**Comment by juliomarcos** [comment]
Any idea if this extension can be done while also using the contentful extension?

**Comment by jescalan** [comment]
It could in theory, but would make things a little more complex. It would need to come after contentful in the plugin order, and would need to take in a shared object containing some contentful data.

**Comment by juliomarcos** [comment]
Woow, thank you for the fast response.
What method should I define to run my extension only after contentful has finished? I've tried to do that using setup but it didn't work.

**Comment by jescalan** [comment]
You'd need to use the `ordered` property on the extensions you need to run in a specific order to accomplish this. More details here on this: http://roots.cx/docs/extensions!

**Comment by juliomarcos** [comment]
Great thanks. I'm not going to use the contenful object to do that, but instead, I'll inspect our html files because not all content comes from contentful.
