### ISSUE TITLE
npm install failing - Couldn't read dependencies

### ISSUE THREAD

**Issue by pranaykarodi** [jenius/roots#641]
Please check the following report

C:\Pranay\Cloned_FrontEnd>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli
.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! file C:\Pranay\Cloned_FrontEnd\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'k' at 7:29
npm ERR!     "test": ".\node_modules\karma\bin\karma",
npm ERR!                             ^
npm ERR! File: C:\Pranay\Cloned_FrontEnd\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Pranay\Cloned_FrontEnd\npm-debug.log

Can't see any error in the address provided. It is able to find package.json. What can be the issue?

**Comment by hhsnopek** [comment]
Could you provide your package.json?

**Comment by pranaykarodi** [comment]
{
  "name": "tracklabs-angular-client",
  "version": "0.0.1",
  "description": "AngularJS based client for the truck and load management system",
  "main": "index.js",
  "scripts": {
    "test": ".\node_modules/karma/bin/karma",
    "start": ".\node_modules/http-server/bin/http-server"
  },
  "repository": "bitbucket:kamal083/angular-client.git",
  "contributors": [
    {
      "name": "Kamal Mewada",
      "email": "kamal.mewada.nitt@gmail.com"
    },
    {
      "name": "Rishi Rajasekaran",
      "email": "rajasekaran.rishi@gmail.com"
    },
    {
      "name": "Siddarth Iyer",
      "email": "mindstormer619@gmail.com"
    }
  ],
  "license": "ISC",
  "devDependencies": {
    "angular-mocks": "^1.3.15",
    "http-server": "^0.8.0",
    "karma": "^0.12.32",
    "karma-chrome-launcher": "^0.1.12",
    "karma-jasmine": "^0.3.5"
  }
}

**Comment by pranaykarodi** [comment]
I changed the "\" in the 6th and 7th line to "/" after posting my query here. Hence the npm install ran successfully but them npm start created the problem. :( 


C:\Pranay\Cloned_FrontEnd>npm start

> tracklabs-angular-client@0.0.1 start C:\Pranay\Cloned_FrontEnd
> .
ode_modules/http-server/bin/http-server

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! tracklabs-angular-client@0.0.1 start: `.
npm ERR! ode_modules/http-server/bin/http-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tracklabs-angular-client@0.0.1 start script '.
npm ERR! ode_modules/http-server/bin/http-server'.
npm ERR! This is most likely a problem with the tracklabs-angular-client package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     .
npm ERR! ode_modules/http-server/bin/http-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls tracklabs-angular-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Pranay\Cloned_FrontEnd\npm-debug.log

**Comment by pranaykarodi** [comment]
And here is my http-server file

#!/usr/bin/env node

var colors     = require('colors'),
    httpServer = require('../lib/http-server'),
    portfinder = require('portfinder'),
    opener = require('opener'),
    argv = require('optimist')
      .boolean('cors')
      .argv;

if (argv.h || argv.help) {
  console.log([
    "usage: http-server [path] [options]",
    "",
    "options:",
    "  -p                 Port to use [8080]",
    "  -a                 Address to use [0.0.0.0]",
    "  -d                 Show directory listings [true]",
    "  -i                 Display autoIndex [true]",
    "  -e --ext           Default file extension if none supplied [none]",
    "  -s --silent        Suppress log messages from output",
    "  --cors             Enable CORS via the 'Access-Control-Allow-Origin' header",
    "  -o [path]          Open browser window after starting the server",
    "  -c                 Cache time (max-age) in seconds [3600], e.g. -c10 for 10 seconds.",
    "                     To disable caching, use -c-1.",
    "",
    "  -P --proxy         Fallback proxy if the request cannot be resolved. e.g.: http://someurl.com",
    "",
    "  -S --ssl           Enable https.",
    "  -C --cert          Path to ssl cert file (default: cert.pem).",
    "  -K --key           Path to ssl key file (default: key.pem).",
    "",
    "  -r --robots        Respond to /robots.txt [User-agent: *\\nDisallow: /]",
    "  -h --help          Print this list and exit."
  ].join('\n'));
  process.exit();
}

var port = argv.p || parseInt(process.env.PORT, 10),
    host = argv.a || '0.0.0.0',
    log = (argv.s || argv.silent) ? (function () {}) : console.log,
    ssl = !!argv.S || !!argv.ssl,
    proxy = argv.P || argv.proxy,
    requestLogger;

if (!argv.s && !argv.silent) {
  requestLogger = function(req, res, error) {
    var date = (new Date).toUTCString();
    if (error) {
      log('[%s] "%s %s" Error (%s): "%s"', date, req.method.red, req.url.red, error.status.toString().red, error.message.red);
    } else {
      log('[%s] "%s %s" "%s"', date, req.method.cyan, req.url.cyan, req.headers['user-agent']);
    }
  };
}

if (!port) {
  portfinder.basePort = 8080;
  portfinder.getPort(function (err, port) {
    if (err) throw err;
    listen(port);
  });
} else {
  listen(port);
}

function listen(port) {
  var options = {
    root: argv._[0],
    cache: argv.c,
    showDir: argv.d,
    autoIndex: argv.i,
    robots: argv.r || argv.robots,
    ext: argv.e || argv.ext,
    logFn: requestLogger,
    proxy: proxy
  };

  if (argv.cors) {
    options.cors = true;
  }

  if (ssl) {
    options.https = {
      cert: argv.C || argv.cert || 'cert.pem',
      key: argv.K || argv.key || 'key.pem'
    };
  }

  var server = httpServer.createServer(options);
  server.listen(port, host, function () {
    var canonicalHost = host === '0.0.0.0' ? '127.0.0.1' : host,
        protocol      = ssl ? 'https:' : 'http:';

    log('Starting up http-server, serving '.yellow
      + server.root.cyan
      + (ssl ? (' through'.yellow + ' https'.cyan) : '')
      + ' on: '.yellow
      + (protocol + '//' + host + ':' + port).cyan);

    if (typeof proxy === 'string') {
      log('Unhandled requests will be served from: ' + proxy);
    }

    log('Hit CTRL-C to stop the server');
    if (argv.o) {
      opener(
        protocol + '//' + canonicalHost + ':' + port,
        { command: argv.o !== true ? argv.o : null }
      );
    }
  });
}

if (process.platform === 'win32') {
  require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
  }).on('SIGINT', function () {
    process.emit('SIGINT');
  });
}

process.on('SIGINT', function() {
  log('http-server stopped.'.red);
  process.exit();
});

**Comment by hhsnopek** [comment]
1. You have multiple errors within your `package.json`, use this site to correct the issues: http://package-json-validator.com/
2. I'm unsure what is wrong with your code you've pasted but I don't see any roots problems in that or in your package.json

**Comment by pranaykarodi** [comment]
It should not contain any issue, as this package.json working fine for ubuntu systems. I tried to do it in windows 8.1, hence it is showing error. I am doing it for the first time so can't see which compatability issue i am missing here. npm install has worked. This syntax error in the 'start' script is stranger. Can't see which '.' it is not able to recognize.

**Comment by thiagodebastos** [comment]
It has been a long time since I tried roots and unfortunately on my first attempt I am facing the same issue, but on a Mac:
node -v 5.0.0
npm -v 3.3.6

❯ npm install roots -g                                                                                                                                                   [07:48:47]
npm ERR! git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e: Cloning into bare repository '/Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e'...
npm ERR! git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e: github.com[0: 192.30.252.129]: errno=Operation timed out
loadDep:st
npm WARN install Couldn't install optional dependency: Command failed: git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e
npm WARN install Cloning into bare repository '/Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e'...
npm WARN install fatal: unable to connect to github.com:
npm WARN install github.com[0: 192.30.252.129]: errno=Operation timed out
npm WARN install
npm WARN install
fetchMetadata   
>>> elapsed time 1m42s
