### ISSUE TITLE
Node-sass not compiling

### ISSUE THREAD

**Issue by wojomike** [jenius/roots#642]
i've got node-sass installed and i changed the css pipeline in app.coffee to look for *.scss instead of *.styl. i've created a main.scss file in the css directory however it is not compiling. i feel like i'm missing something obvious but i'm beating my head against the wall wondering why accord isn't picking up on the switch to .scss files. I'm using roots v.3.0.4

Any suggestions would be greatly appreciated!

**Comment by hhsnopek** [comment]
Hey @wojomike have you seen this? https://github.com/jenius/roots/issues/614

**Comment by jenius** [comment]
Should be set now with the latest release
