### ISSUE TITLE
PostCSS is not working in the current (v3.0.4) roots version

### ISSUE THREAD

**Issue by janviehweger** [jenius/roots#643]
**Problem:**
* [PostCSS] (https://github.com/postcss/postcss) is not working in the current (v3.0.4) roots version

**Reason:**
* missing [PostCSS adapter](https://github.com/jenius/accord/blob/master/docs/postcss.md) in the included accord version `(v0.18.0)`

**Workaround:**
(by [EnMod] (https://github.com/EnMod), as discussed on [Gitter](https://gitter.im/jenius/roots)):

* in the Roots module directory, update Accord using the git master for now, should be published to NPM soon
* In your project directory: npm install postcss --save
* Put the following in your app.coffee:
``` coffeescript
foo = require 'postcss-plugin-you-want-to-use'
module.exports = 
    postcss:
        use: [foo()]
```
* Name files you'd want to have postprocessed as file.css, optionally adding extensions for whatever else you want to use for preprocessing, for example `file.css.styl` for Stylus-to-PostCSS.

**Comment by jenius** [comment]
We just need to update accord and push a new roots release. I'll do this tomorrow, sorry -- have been off the grid for the last 2 weeks traveling.

**Comment by jenius** [comment]
Roots `3.1.0`, released today, will work with postcss. Sorry about the delay!
