### ISSUE TITLE
Apply stylus plugins to jade filters

### ISSUE THREAD

**Issue by hhsnopek** [jenius/roots#645]
Unfortunately when you included a stylus file with jade the `:stylus` filter you're unable apply stylus plugins (when using roots). Here's the work around for it: http://stackoverflow.com/questions/12272936/is-it-possible-to-use-stylus-plugins-with-inline-stylus-code-embedded-in-a-jade
It would be awesome if we were able to add this workaround so we may inline stylus while still using plugins.

**Comment by jenius** [comment]
So this is a little dangerous as it appears as if you need to patch jade's source, which is definitely not something we can or want to get involved with.

However, if there is a way to make this modification through an option passed in to jade (which is preferred, potentially a pull request could make this happen, or it is already possible through more tinkering), we could add an option to accord to include plugins like this, then it would automatically become available in roots.

Here's my suggestion. Make a little example project with pure jade and stylus used via js to compile, and see if you can make this happen without patching either of the sources. If you can, open up an issue in accord to add this as an option. If not, figure out the cleanest way to expose it by modifying jade's source and submit a pull request. Once that is accepted, we can move forward with implementing it through accord.
