### ISSUE TITLE
Runs app.js, but only if app.coffee exists

### ISSUE THREAD

**Issue by cspotcode** [jenius/roots#650]
Is this intended behavior?  I was trying to set up a roots project with my app file written in JavaScript instead of CoffeeScript. (just personal preference)

With only an `app.js` file, roots doesn't read it.  With an `app.js` and an `app.coffee` file, roots only reads the `app.js` file.

Is it doing `require('./app')` or something?

Thanks for your time.

**Comment by jenius** [comment]
Hey there! Yes, it is. Roots does not support `app.js`, the fact that it works under any condition was unknown to me. If there's enough demand for it, we could add support for this, but `app.coffee` is really just a very simple configuration file, not one in which a lot of coding needs to be done, so coffee just makes it less to write and cleaner.

**Comment by cspotcode** [comment]
I see, makes sense.  I'll switch back to using app.coffee.  Thanks for the
explanation!

**Comment by jenius** [comment]
:+1:
