### ISSUE TITLE
Why is a fresh roots install giving me a deprecation warning on compile?

### ISSUE THREAD

**Issue by pjv** [jenius/roots#651]
On a fresh install of roots and the creation of a new site project, each compile gives me this warning:

`compiling... Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead`

Shouldn't the project that gets created set up app.coffee so the compile happens in accord with the preferred method of calling autoprefixer?

And the warning is a little cryptic about where/how to make that change. Can someone provide an example of an app.coffee that calls autoprefixer correctly?

**Comment by jenius** [comment]
Sorry, I thought this has been resolved but apparently it has not. If you just go to your `package.json` file and update `autoprefixer-stylus` to `0.7.0`, this will solve the problem.

**Comment by declandewet** [comment]
damnit @jenius you beat me to it! :P

**Comment by pjv** [comment]
Perfect. Thanks!

Now how about this deprecation warning (last one):

`Transformers.markdown is deprecated, you must replace the :markdown jade filter, with :marked and install jstransformer-marked before you update to jade@2.0.0`

**Comment by dbox** [comment]
@pjv do `npm install jstransformer-marked` then change all `:markdown` instances to `:marked`

btw @jenius this is what was going on with axis-www

**Comment by jenius** [comment]
Didn't we update the roots-base template with this set of changes as well?

**Comment by dbox** [comment]
no, i think only an axis bump. I'll do it

**Comment by pjv** [comment]
thanks all. no more deprecation warnings.
