### ISSUE TITLE
Data save causes reload without content update

### ISSUE THREAD

**Issue by ArrayKnight** [jenius/roots#653]
I am utilizing the records extension and have a json file in my data folder. I have successfully pulled data from the file into my templates and have the watcher running. When I save changes to the json file, the compile task runs and the browser reloads, but the new data is not reflected. It requires a restart of the watcher to get the new data to come through.

**Comment by jenius** [comment]
This should be filed in https://github.com/carrot/roots-records

At the moment, roots-records caches your data when it starts watching for better performance, and does not constantly scan it for changes. Integrating this type of behavior would be possible but fairly challenging -- maybe someone could help with it though!
