### ISSUE TITLE
After update from 3.1.0 to 3.2.1 no images are showing

### ISSUE THREAD

**Issue by terusus** [jenius/roots#655]
I updated only the global roots app and no image assets are showing on the website (project created and working with 3.1.0).

I get an error result in the browser saying "connection refused" to the specific image file.

**Comment by danlin** [comment]
same here but with a fresh 3.2.1 project. i move down to 3.1.0 and all works as expected.

**Comment by jenius** [comment]
Hey guys, really sorry this is happening. We have isolated the bug, it's something very strange in charge, roots' web server. It somehow made it through all the tests for 2-3 levels deep of modules, even through 95% coverage on all of them. Crazy. Either way, this bug will be patched up within the next week, for now you can stay on `3.1.x`. Really sorry that this happened, and will update here personally as soon as it's fixed and a patch release is out!

:bow:

**Comment by danlin** [comment]
3.2.2 Still have this bug.
Running in Production works.
The bug is based on this middeware https://github.com/samccone/infestor
Without content replacement all works fine.

**Comment by jenius** [comment]
Ah thanks for digging this up. This is strange, as the version of infestor is the same as `3.1.x` in `3.2.2`, so I'm having trouble seeing why it would act differently. I'll dig into it a little further though when I have a minute!

**Comment by dbox** [comment]
Can verify happening in 3.2.2

**Comment by jag20101** [comment]
^ Yup. Running into the same problem :/

**Comment by CalvinLeGassick** [comment]
Am experiencing. Can confirm.

**Comment by jenius** [comment]
Hey there everyone!

So I think I have this issue worked out. I've applied a fix and tested it on one project that I was having issues with and it worked. However, I'd like to make sure that I really have this right before publishing this next patch.

For anyone that has an example project showing the issue, could you link me up to this project and/or share it with me so I can test it and make sure everything is resolved?

**Comment by danlin** [comment]
@jenius i don't know how other systems handle transfer-encoding: chunked header. On my Mac OS X System with Safari i have broken connections on every Image file and other strange things happening like missing text.

with my infestor patch i have no issues anymore.

**Comment by terusus** [comment]
I cannot share the project with you but I can test out the patches myself.

**Comment by dbox** [comment]
I'm not even sure you need a sample project. I assume all 3.2.2 projects have broken images.

Here's a repo:

https://github.com/dbox/roots-image-test

Image worked in 3.1.0. Upgraded globally to 3.2.2 and image was broken.

**Comment by jenius** [comment]
Still working on fixing this guys. Sorry for the delays!

**Comment by molovo** [comment]
@jenius did you get anywhere with this? If you haven't I might take a look under the hood

**Comment by dbox** [comment]
@molovo Yes, it's fixed here: https://github.com/jenius/roots/pull/681
