### ISSUE TITLE
add/normalize template reference

### ISSUE THREAD

**Issue by hhsnopek** [jenius/roots#657]
Add: `roots new <name> --tpl <tplName>`

As a connivence when you are accessing templates with `roots tpl` but unable to select a template via `roots new <name> --tpl <tplName>`

**Comment by jenius** [comment]
I'm not sure I understand... could you clarify a little here?

**Comment by hhsnopek** [comment]
yeah so right now when you wanna access templates without creating a new project you're able to use both: `roots tpl ...` & `roots template ...`. When we create a project with a template you must use `roots new <name> --template <templateName>` with no alias to `roots new <name> --tpl <tplName>

**Comment by hhsnopek** [comment]
tl;dr: alias `--template` to `--tpl`

**Comment by jenius** [comment]
Sure, works for me. Very simple change too. Want to PR it in, or I can do it?

**Comment by hhsnopek** [comment]
if you're able to get it done that would be great, otherwise I can get to it later this weekend

**Comment by hhsnopek** [comment]
thank you :dancer:
