### ISSUE TITLE
 segmentation fault roots watch

### ISSUE THREAD

**Issue by dbox** [jenius/roots#659]
I (and others) get this quite often now:

 `segmentation fault roots watch` 

I did a search and haven't seen any information on this specific error. Basically the watcher will shut down randomly, then show the error. After restarting `roots watch`, everything works normally again until, eventually it shows the `segmentation fault` again.

At this time I can't pin down a specific action that is triggering the error.

At the very least could this be patched so that if this error happens that the watcher automatically restarts?

**Comment by jenius** [comment]
Hm, weird. Segmentation faults are outside of roots' domain, this is a severe memory issue with the machine. We're not really able to catch errors like this or handle them with node... is there anything in particular you can do to replicate errors like this? Could you watch your memory and see if it's maxing out?
