### ISSUE TITLE
[V 3.1.0] problems setting the output variable in app.production.coffee

### ISSUE THREAD

**Issue by ganar** [jenius/roots#663]
I have a file named `app.production.coffee` the sets the place were I want *roots* to build my production files for the project.

My variable  `output` is set like this:

```
output       = '../../www/ia'

```
but even though on executing `roots compile -e production` it seems to be doing something, and no error is thrown, the corresponding directory is empty.

I also tried doing 

```
output       = 'ia'

```
With the same result. What do you suggest I do in this case?

**Comment by jenius** [comment]
In `app.coffee`, `module.exports` is an object. Therefore, you must use the key/value syntax as in other objects, not assigning of a variable.

Changing this to `output: '../../www/ia` will work. I just tested this with a fresh project :grinning:

**Comment by ganar** [comment]
@jenius Jeff: thanks a lot for your help. Please consider linking together the article on [roots configuration](http://roots.cx/docs/configuration)  and [environments](http://roots.cx/docs/environments) or give a more complete example at the end of *environment*. The documentation is not very clear for us noobs.

**Comment by jenius** [comment]
No problem! Would you be willing to contribute these changes to the documentation? I'm not sure I understand exactly what clarifications you are after, so I'm sure you'd do a better job than me!

https://github.com/carrot/roots-www
