### ISSUE TITLE
JS Bundle is cut out

### ISSUE THREAD

**Issue by edravis** [jenius/roots#665]
I'd love to reproduce the steps but I was just using roots as always and then I realise a really strange thing. My `bundle.js` starts with `else`! I've checked and the `bundle.js` file in the public directory is perfectly fine so I guess it's the watcher that's getting this file wrong.

I don't know what else can I say. If you think there's some information that I can share there's no problem, I want to help. 

Important facts:
* I'm using `browserify`
* I don't ignore a single file on `scripts/`
* I run `http-server` into `public/` and it works like a charm
* The roots compiler doesn't output any log beyond: `compiling... done!` 

**EDIT**: Related to #654

**Comment by Leeds-eBooks** [comment]
I think this is the same bug I was epxeriencing here: #654 

I think if you roll back to `3.1.0` you'll stop seeing this problem.

**Comment by edravis** [comment]
Works like a charm, thanks @Leeds-eBooks 
Btw @jenius , I've notice that only happen when `watch` not with `compile`. Maybe this is some important info.
