### ISSUE TITLE
Livereload not working

### ISSUE THREAD

**Issue by tiktuk** [jenius/roots#669]
Just tried out Roots (v3.2.2 on node v0.12.4) and couldn't get Livereload to work.

I followed the guide and created a new project with ``roots new example`` and ``roots watch``. When I edit a file the change is picked up and the project is compiled as expected. It is not automatically reloaded though.

On Safari (latest, v8.0.8) I noticed that the ``/__roots__/main.js`` is not injected (I found it in Chrome). Checking the Web Inspector Safari is showing the following message in the Console:

    [Error] Failed to load resource: The network connection was lost. (localhost, line 0) (http://localhost:1111/)

This message is showing every time I reload Safari manually.

This error is not showing up in Chrome but the Livereload extension is complaining: "Could not connect to Livereload server".

Searching the Roots source a bit I'm also puzzled: Where is the Livereload server supposed to be started and by which module?

**Comment by jenius** [comment]
Hey there, really sorry about this. @samccone might be able to help point me in the right direction for a fix here

**Comment by Leeds-eBooks** [comment]
@tiktuk Are you using an environment argument? I have found that LiveReload doesn't work if you use `roots watch -e xyz`. For example, a basic project with an `app.coffee` works fine – change the filename to `app.dev.coffee` and run `roots watch -e dev` and livereload doesn't work.

**Comment by jenius** [comment]
We have a branch in the works that will fix this issue. Tested and functional. I'm going to get it released as soon as I can. Just wanted to let you guys know! It will work with all environments as well :grinning:

**Comment by Leeds-eBooks** [comment]
That's brilliant news! Thanks very much. Is that the browser sync branch?

**Comment by jenius** [comment]
Yes indeed it is!

**Comment by tiktuk** [comment]
Sounds good, thanks for working on it, @jenius :) .

**Comment by jenius** [comment]
Fixed in v4
