### ISSUE TITLE
Running multiple versions of roots in the same machine

### ISSUE THREAD

**Issue by ganar** [jenius/roots#670]
I'm sorry for the noob question: I have multiple projects, running different versions of roots.

How do I make a `roots watch` of a project made in *roots 2.4.1*?  The new *roots 3.1.0* does not output correctly and the configuration does not seem to force the old version of roots upon `roots watch`

**Comment by joshrowley** [comment]
One solution is to specify the roots version in `package.json` and then add an alias in your bash profile: `alias roots-local="./node_modules/roots/bin/roots"`, then run `roots-local` whenever you want to run the version of roots specific to the project you're working on.

**Comment by jenius** [comment]
Sorry for the late followup, but yeah that should do this trick! Thanks Josh :grinning:

**Comment by ganar** [comment]
@joshrowley can you be more specific on were is `package.json` located?. I don't program in this technology, I'm a roots user. How do you manage to keep both versions in the same machine?

**Comment by Leeds-eBooks** [comment]
A better solution would be to install roots _locally_: `npm install roots@2.4.1` **(no `-g`)**. Then in your `package.json` (in the root directory of your roots project), add the following to the `scripts` key:

```json
"watch": "roots watch"
```

Then you just run `npm run watch` and it will use the local version of roots (local to the project).

**Comment by ganar** [comment]
Thanks @Leeds-eBooks: do I have to `cd` to the directory were the project is before doing the install? will this affect the other, more recent, roots installation?

**Comment by Leeds-eBooks** [comment]
Yes you do, and no it won't :)

**Comment by Leeds-eBooks** [comment]
If you don't already have a `package.json`, you'll need to run `npm init` in the project directory first.

**Comment by ganar** [comment]
Excellent! thanks a lot for your help @Leed-eBooks

**Comment by Leeds-eBooks** [comment]
No problem! Let me know if you have any problems.

**Comment by ganar** [comment]
@Leeds-eBooks all hell broke loose

I switched to *El Capitán* and roots 2.1.4 no longer works. Period. The error log for the —attempted— installation is 1.5MB.

Do you have any idea of which version of Node should I install to get it to run again? I'm trying to use `NVM` to install an old version and see if I can bring this old project (2 years old) back from the dead.

**HINT** I have another machine running *El Capitán* with this project working. Is there anyway that I can use to move the binaries for roots to my machine that may allow me to keep owrking on the project?

Any help is truly appreciated

## Tail of the error in the teminal

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (.nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Volumes/Legacy/Users/ganar/.nvm/versions/io.js/v3.3.1/bin/iojs" ".nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Legacy/webserver/projects/eck/bocetos/redesign/node_modules/roots/node_modules/node-sass
gyp ERR! node -v v3.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.4.0
npm ERR! argv "/Volumes/Legacy/Users/ganar/.nvm/versions/io.js/v3.3.1/bin/iojs" "/Volumes/Legacy/Users/ganar/.nvm/versions/io.js/v3.3.1/bin/npm" "install" "roots@2.1.5"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.8.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.8.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Legacy/webserver/projects/eck/bocetos/redesign/npm-debug.log
```

**Comment by declandewet** [comment]
@ganar 

It could also very well be that you might have forgot to install all the necessary dependencies Node.js needs to build native modules, one of which seems to be Node.js itself. According to this line in your error:

```
gyp ERR! stack     at ChildProcess.onExit (.nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
```

You're attempting to build a legacy Node.js project with `io.js`.

Try running this first:

```
$ nvm install 0.10 && nvm use 0.10
```

Then try `$ npm install roots` once again.

If that still doesn't work, and you still get references to `node-gyp` in your error log, you might need to install Python (specifically version `2.7`, if I remember correctly) as well as [`Xcode`](https://developer.apple.com/xcode/download/) (You also need to install the `Command Line Tools` via `Xcode`. You can find this under the menu `Xcode -> Preferences -> Downloads`. This step will install `gcc` and the related toolchain containing `make`)

> Do you have any idea of which version of Node should I install to get it to run again? I'm trying to use NVM to install an old version and see if I can bring this old project (2 years old) back from the dead.

You can infer this information from the [`engines` field in `package.json` on the branch that contains `v2.1.4`](https://github.com/jenius/roots/blob/v2.1.4/package.json#L80) [(permalink)](https://github.com/jenius/roots/blob/4f7a0499194a8358a68b81496f8f7a049c1d86b4/package.json#L80) - according to the link, the `node` version should be greater than or equal to `v0.8`. (although, I do remember having Node.js `v0.10.x` compatibility in Roots `v2.x`)

**Comment by ganar** [comment]
@declandewet Great answer! So clear and thorough at the same time! Kudos! I particularly appreciate the link to the specific line on `package.json` with the dependency. I'm a designer that uses roots, not a node developer: the curve to use, and, above all, maintain the projects over time, using this kind of technologies has been quite steep.

My roots 2.1.4 installation is finally up and running, the only change to your instructions that I would appreciate very much  in your answer —for all of us noobs in the audience— is this:

````
npm install -g roots@2.1.4
````

It does not work without the `-g` (global) option, and the roots version has to be specified. Other than that the answer is perfect.
