### ISSUE TITLE
PostCSS and lostgrid

### ISSUE THREAD

**Issue by AleksejDix** [jenius/roots#673]
hello i am trying to make roots work with postcss and the  [lost grid](https://github.com/corysimmons/lost)

```
postcss:
  use:[lost(),autoprefixer()]

```

can you help me ?

**Comment by michaelkornblum** [comment]
Most definitely sir. How would you like to contact me?

**Comment by michaelkornblum** [comment]
Here are the steps I went through to get it to work.

1. Install npm depenencies. The ones you want to look at are accord, postcss version 4, and lost. From the command line, enter:

```
  npm install --save accord postcss@4  lost

2. modify the app.coffee file

At the top of the app.coffee file you will want to add these variables.

  accord = require 'accord'
  postcss = accord.load 'postcss'
  lost = require 'lost'

Next, you'll want to add the postcss configuration to the bottom of your app.coffee file.  These two lines of code should do the trick.

  postcss:
    use: [lost()]

3. Change css file extension names.
If you're using stylus along with postcss, you'll need to change the file names of all the files living in your assets/css directory from <filename>.styl to <filename>.css.styl. If you're not using stylus just change the filenames from <filename>.styl to <filename>.css.

4. Go forth and merrily postprocess :)

**Comment by AleksejDix** [comment]
thx worked like a charm, i forgot accord.
but i still have problems it compiles the files when i touch them and it should compile them only when i save

**Comment by jenius** [comment]
Glad this worked out, and thanks for the amazing detailed instructions @michaelkornblum!
