### ISSUE TITLE
production compiled produces "[object Object]" in build css

### ISSUE THREAD

**Issue by i8ramin** [jenius/roots#675]
From a brand new roots project, when I run ```roots compile -e production``` I get the following side of the generated ```public/css/build.1441a7909c087dbbe7ce59881b9df8b9.css```file:

```
[object Object]
```

Node ver: v0.12.7
package.json:
```
{
  "name": "wework.com",
  "description": "WeWork marketing site",
  "dependencies": {
    "autoprefixer-stylus": "0.7.x",
    "axis": "0.4.x",
    "coffee-script": "1.9.x",
    "css-pipeline": "0.2.x",
    "jade": "1.x",
    "js-pipeline": "0.2.x",
    "jstransformer-marked": "0.0.x",
    "marked": "0.3.x",
    "rupture": "0.6.x",
    "stylus": "0.51.x"
  }
}
```

Any way to debug this or compile in verbose mode to see what is happening?

**Comment by jenius** [comment]
Hey there Ramin!

Really sorry about this, it's my fault and is the result of me not keeping the roots default template as up-to-date as it should be. You can resolve this immediately by upgrading the version of `js-pipeline` to `0.3.x` in your `package.json` file. I will update it to the correct version in the roots default template right now to prevent this issue from happening again.

Thanks for the thorough report, and sorry about this issue!

**Comment by i8ramin** [comment]
works like a charm, thanks!
