### ISSUE TITLE
Handlebars 4.0.2 is not currenlty supported.

### ISSUE THREAD

**Issue by ryanAbbott** [jenius/roots#678]
Hello!
I tried creating a handlebars template (created an about.handlebars) and got the following error after `roots watch`:

[Error: handlebars version 4.0.2 is not currently supported]

I reinstalled handlbars version ~3 and it was error free.

**Comment by jenius** [comment]
Hey there! Thanks for catching this. It's actually an upgrade to be made to [accord](https://github.com/jenius/accord) -- is there any way you could file an issue there? We'll get it fixed up as soon as we can :grinning:

**Comment by ryanAbbott** [comment]
Done. Thanks for the quick the response.
