### ISSUE TITLE
postcss block not working in app.coffee?

### ISSUE THREAD

**Issue by i8ramin** [jenius/roots#683]
I've been trying to use postcss in my project but it doesn't look like the postcss config block is being read at all. I am able to get most postcss plugins working using `poststylus`, but just defining them under the `postcss` config block does nothing. Any tips or docs on making this work?

**Comment by declandewet** [comment]
Hi @i8ramin 

Be sure to check that all of the following is in place:

- You have installed `postcss` in your project via `npm install postcss --save`
- Your `postcss` config block follows the correct syntax - Here's an example:
  - ![](http://infinit.io/_/GRe4a2b.png)
- At the very least, your main Stylus file (e.g. `master.styl`) should have the file extension `.css.styl`
- Optional, but a nice-to-have, is the ability to inline `@import`s of regular CSS files in Stylus using the `inline stylus` option:
  - ![](http://infinit.io/_/hU2LeHz.png)

That should kick [Multipass Compilation](http://roots.cx/docs/multipass) into gear and get PostCSS working!

**Comment by FranzSkuffka** [comment]
It might make sense to add this to the readme and documentation as an example use of multipass compilation.

**Comment by jenius** [comment]
I think that would be great! Would you be willing to submit a PR for this @FranzSkuffka?

**Comment by FranzSkuffka** [comment]
@jenius Confirmed.
It's on my todo list now :)

**Comment by FranzSkuffka** [comment]
@i8ramin was also asking for poststylus in specific. I used it in https://github.com/FranzSkuffka/gulp-stylus-pipeline but it did not improve this module. I do not think poststylus is actually ready yet but it might make sense to integrate it sooner or later.

**Comment by hhsnopek** [comment]
I've actually used poststylus and it works great for the plugin I was using
