### ISSUE TITLE
Can't install Roots globally with npm

### ISSUE THREAD

**Issue by maxx1128** [jenius/roots#686]
Every time I try to install roots I keep getting the following error on my command line:

    > fsevents@0.3.8 install /usr/local/lib/node_modules/roots/node_modules/chokidar/node_modules/fsevents
    > node-gyp rebuild

    /usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found
    npm WARN optional dep failed, continuing fsevents@0.3.8
    /usr/local/bin/roots -> /usr/local/lib/node_modules/roots/bin/roots

    > roots@3.1.0 postinstall /usr/local/lib/node_modules/roots
    > node ./post_install.js

    sh: node: command not found
    npm ERR! Darwin 14.5.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "roots"
    npm ERR! node v4.0.0
    npm ERR! npm  v2.14.2
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn

    npm ERR! roots@3.1.0 postinstall: `node ./post_install.js`
    npm ERR! spawn ENOENT
    npm ERR! 
    npm ERR! Failed at the roots@3.1.0 postinstall script 'node ./post_install.js'.
    npm ERR! This is most likely a problem with the roots package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./post_install.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls roots
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/maxwellantonucci/npm-debug.log

I already have bower installed globally and have installed other dependencies before, so am not sure what's going wrong.

**Comment by thiagodebastos** [comment]
I'm not sure if this is relevant, but I am facing the same issue on one of my macs.
I get this error though:

```
npm ERR! git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e: Cloning into bare repository '/Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e'...
npm ERR! git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e: fatal: unable to connect to github.com:
npm ERR! git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e: github.com[0: 192.30.252.128]: errno=Operation timed out
loadDep:st                ▐ ╢██████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░npm WARN install Couldn't install optional dependency: Command failed: git clone --template=/Users/debastost/.npm/_git-remotes/_templates --mirror git://github.com/jenius/st.git /Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e
npm WARN install Cloning into bare repository '/Users/debastost/.npm/_git-remotes/git-github-com-jenius-st-git-75440a74bcfef19581af498df6a5644e'...
npm WARN install fatal: unable to connect to github.com:
npm WARN install github.com[0: 192.30.252.128]: errno=Operation timed out

```

It's quite strange considering I dont have an issue with any other repos on GitHub?

**Comment by jenius** [comment]
Never seen this one before. Definitely not an issue with roots through haha, it's an internet thing.

**Comment by thiagodebastos** [comment]
Sometimes I wish the internet behaved nicely just for one whole day, just
one! I'll look deeper into it as soon as I get a chance!

**Comment by FranzSkuffka** [comment]
Probably not but possibly a fix: `sudo chmod a+rx /usr/local/bin /usr/local/bin/node`

http://yeoman.io/learning/faq.html

**Comment by pattyok** [comment]
For anyone coming across the postinstall.js error. Update npm to the latest stable version and you should be good to go.
