### ISSUE TITLE
Roots watch not noticing any changes

### ISSUE THREAD

**Issue by kyotoprotokollet** [jenius/roots#688]
Running roots watch does not pick up any changes for me. I get no error message, it just doesn't see any changes that I make in my code. Any ideas?

**Comment by FranzSkuffka** [comment]
Which system are you on? Does the server serve the correct files?

**Comment by jenius** [comment]
Yeah I can't replicate this issue. Need a lot more detail here.

**Comment by kyotoprotokollet** [comment]
I was on MacOS 10.9.5. Anyway, updating Node & NPM seems to have fixed this for me.

**Comment by smth** [comment]
I'm getting this issue at the moment. Running `roots watch` compiles successfully, but does not detect changes after that (without cancelling the watcher and running again).

I'm using the latest version of Roots, but working on an old site that I built on version 2 or 3 I think. I got a few warnings when installing the package:

```
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
```
