### ISSUE TITLE
Check directory before running compiles

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/roots#689]
I just ran into a problem similar to https://github.com/jenius/roots/pull/662
but it was caused by accidentally running roots inside the `views` directory.

It might make sense to check if the current directory is actually the root of a roots project.

_edit_:
In fact I am running into the exact same issue, but this might make sense anyways.

**Comment by FranzSkuffka** [comment]
I get

```
ENOENT, no such file or directory '/Users/jan/ufo2/assets/css/views/layout.jade']

Potentially unhandled rejection [10] Error: /Users/jan/ufo2/assets/css/master.css.styl:1
  > 1| extends views/layout
    2| 
    3| include views/_mixins
    4| 
```

on every compile except the first after initializing the watcher.

I do not encounter this bug when I do not define a `template` for a content type in roots-contentful.

**Comment by jenius** [comment]
Sorry we are not going to include a check for the current directory. That's the developer's responsibility to know which directory they are in, not roots'. As far as the second issue, is this the same issue or a different one? If it's a different one, could you open a different issue and please add a bit more detail so we can replicate this?

**Comment by FranzSkuffka** [comment]
This is probably some misconfiguration of the project or a naming conflict with some internal variables. Have to fix this myself. Thanks though!
