### ISSUE TITLE
Use rebase instead of merges.

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/roots#690]
Using a rebase instead of a merge when consuming pull requests is a way to maintain a linear commit history

**Comment by jenius** [comment]
I like having merges when a branch was merged. It shows a concrete piece of work being done then merged back in. Rebase can keep the timeline and the merge bubbles clean, and each branch should be rebased before being merged, but I do not think just making everything totally flat is a good way to keep track of history.

**Comment by FranzSkuffka** [comment]
Thank you for evaluating. :smile:
