### ISSUE TITLE
Support for Ghost API

### ISSUE THREAD

**Issue by desiredpersona** [jenius/roots#695]
Is it possible to use roots with ghost

Does any template exist?

Ghost now has an API http://api.ghost.org/v0.1/docs

Im currently using Buster static site generator (has some issues) to host my ghost blog on Amazon s3 but the project is not maintained anymore. Roots looks like a great maintained alternative

**Comment by jenius** [comment]
Ah this is nice, so now that ghost has an API, we could make a roots extension that is able to pull in ghost posts and mirror them into a static site in much the way we have done with the [wordpress plugin](https://github.com/carrot/roots-wordpress). 

At the moment, I don't have the time on my hands to crank this out, are you at all interested in tinkering with an extension? You can see the wordpress one linked above as an example. It's actually quite simple :grinning:

**Comment by desiredpersona** [comment]
Hey Jeff, appreciate the reply. Ok i understand you are busy. Id love to but i don't have the code skills

**Comment by jenius** [comment]
If you don't have the code skills, it's going to be pretty difficult to use roots. Are you sure?

**Comment by desiredpersona** [comment]
I can use the terminal etc but wouldn't be able to write the plugin myself. Wondering if you could add something to roots website to attract developers interest?

I realise your company wouldn't have use for such a plugin and therefore it wouldn't be a priority

**Comment by jenius** [comment]
Only one way to learn, and I'm here to help :grin: 

No way to make it a higher priority, maybe I'd drop in the gitter chatroom and ask. This is open source software though, using and contributing go hand in hand!

**Comment by desiredpersona** [comment]
Thanks for your help Jeff :smiley: I decided to use Jekyll and write my posts with iA Writer.
