### ISSUE TITLE
Remove "Connected to BrowserSync" display banner when reloading

### ISSUE THREAD

**Issue by eliwilliamson** [jenius/roots#701]
![screen shot 2016-02-18 at 1 43 27 pm](https://cloud.githubusercontent.com/assets/871660/13155943/c9a750c2-d645-11e5-9e33-6dd39c7cf8a5.png)
^ blocks quick checking for navigation development

**Comment by jenius** [comment]
I would love to remove this, but I don't know how! Looked around in the settings and didn't find a way to turn it off. You'd have to open an issue in browser sync asking if they could add a setting to disable this feature.

**Comment by eliwilliamson** [comment]
I found this in their docs but don't know where it is nested in the roots build https://www.browsersync.io/docs/options/#option-notify

**Comment by jenius** [comment]
Ah nice find. Not sure how I missed that. I'll put this in tomorrow and see if it works!

**Comment by jenius** [comment]
Works! Published as `roots@4.0.1` and live now.

**Comment by eliwilliamson** [comment]
you rock @jenius thanks for the fix! Looking forward to the deploy --to gh-pages "ship" issue resolution :+1:

**Comment by milosmijakovac** [comment]
```js
browserSync.init({      
  notify: false
});
```

**Comment by skdineshkumar** [comment]
Can you please help me in where to find the settings? I'm using sublime text 3 plugin for browsersync.

Thanks,

**Comment by jcarignan** [comment]
I am also looking for an answer. I already tried to add `notify: false` to webpack.config.watch.js but no dice. I also don't understand how browsersync-webpack-plugin is set at "^0.6.0" in package.json. Looking at the tags on the repo (https://www.npmjs.com/package/browser-sync-webpack-plugin) looks like 0.6.0 doesn't exist. Apparently the feature was implemented on Jul 3rd, 2017 (https://github.com/Va1/browser-sync-webpack-plugin/issues/41)

**Comment by alinobari** [comment]
For anyone stuck on where to place the `notify: false`, this is the configuration for `gulpfile.js` (v4):
```
function watch() {
    browserSync.init({
        // You can tell browserSync to use this directory and serve it as a mini-server
        server: { baseDir: "./src" },
        notify: false
    });
    gulp.watch("src/*.html").on('change', browserSync.reload);
}

var build = gulp.parallel(watch);
gulp.task('default', build);
```

**Comment by ucarmurat** [comment]
You can fix like this.
Open the folder "sublime Text 3/Packages/Browser Sync/node_modules/browser-sync/lib/**default-config.js**"

and then change the "notify: true," with "notify: false,"

**Comment by LuizCarlosPJr** [comment]
Hello there, can someone please give an insight on how to config this on vs code? i'm using vscode-preview-server extension. Thanks in advance!

**Comment by vdegenne** [comment]
`--no-notify` for the command line ;-)

**Comment by EarthmanWeb** [comment]
It annoys me at the top right, but I still like to have the option to see the banner, just not where it lands...

To that end: this CSS code puts it nicely at the bottom right of the page, or you can use similar non-obtrusive css in your page to change the default style anyway you want...

Enjoy!!!

*Note:  calc might not always work: [check your browser here](https://caniuse.com/calc )
```
#__bs_notify__ {
    position: fixed;
    top: calc(100% - 50px) !important;
    border-radius: 0px !important;
}
```

**Comment by Maxwell200073** [comment]
In windows, go to C:\Users\yourname\AppData\Roaming\npm\node_modules\browser-sync\dist

Replace your name with yours in the above destination. Then find default-config file.  Open that in your text editor and find notify: true,
Mine was on line 330. Just change it to false and save. Congrats!!! That annoying pop-up is gone forever. RIP

**Comment by murtuzaalisurti** [comment]
> ```js
> browserSync.init({      
>   notify: false
> });
> ```

thanks

**Comment by limitlesscreator** [comment]
> C:\Users\yourname\AppData\Roaming\npm\node_modules\browser-sync\dist

thank uuuuuuu

**Comment by albox7** [comment]
The css brutal way....

`#__bs_notify__ { display: none !important; }`

**Comment by vdegenne** [comment]
> The css brutal way....
> 
> `#__bs_notify__ { display: none !important; }`

@albox7 what's brutal is still using browsersync in 2026 👀
