### ISSUE TITLE
[extension] Asciidoctor support

### ISSUE THREAD

**Issue by gristel** [jenius/roots#702]
Hi.

Are there any plans to support Asciidoctor files, along with markup?

Thanks

**Comment by jenius** [comment]
Nope! But would be happy to review a pull request if you'd like to try to add support :grinning:

**Comment by gristel** [comment]
I'm afraid I'm too noobish in this matter to try and attempt that :(
But maybe somebody reading this might have some ideas :)

**Comment by jenius** [comment]
Hey there's only one way to improve! For now I'm going to close the issue since nobody is working on this, but happy to re-open as soon as someone is :grinning:
