### ISSUE TITLE
Setting server.log to anything blows up watcher

### ISSUE THREAD

**Issue by adamkiss** [jenius/roots#703]
If you set `server.log` to anything, e.g. `dev` or `tiny`, watcher blows up on first hit with this:

```
/Users/adam/Sites/test/roots/node_modules/infestor/index.js:86
        opts.injectContent.apply(this, [content, writeEncoding].concat([].slice.call(arguments, 0))),
```

I was debugging this up and down and I think the problem is in the local_server ([Show Github Line](https://github.com/jenius/roots/blob/master/lib/local_server.coffee#L57)), where it calls journalist (Infestor) and should probably call columnist (Morgan). At least, fixing that works for me.

But that's just an idea, I am not proficient with Roots to know if there's logging routing through Infestor to Morgan.

**Comment by jenius** [comment]
Nice catch! Seems like that is the issue. Must have been a typo! Want to submit a PR with a fix to claim the glory?

**Comment by adamkiss** [comment]
I could try, but I am really just dabbling with node :) Gimme a sec
