### ISSUE TITLE
npm modules in frontend

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/roots#705]
I am having troubles using node modules in the frontend. I want to build an Angular2 app using roots.
When I use browserify the compile process takes roughly 4 seconds which is not bearable. js-pipeline  won't compile from node_modules. Transferring them manually does not seem to be the appropriate solution here. Did anyone tackle this yet?

**Comment by FranzSkuffka** [comment]
I am having troubles using node modules in the frontend. I want to build an Angular2 app using roots.
When I use browserify the compile process takes roughly 4 seconds which is not bearable. js-pipeline simply won't compile from node_modules. Transferring them manually does not seem to be the appropriate solution here. Did anyone tackle this yet?

**Comment by jenius** [comment]
How big are the node modules you are loading? Browserify would only take that long if you are loading an absolutely massive amount of code. Take a look at your output file perhaps?

**Comment by FranzSkuffka** [comment]
Angular2 is just huge. I get multi-megabyte files. Thanks for the poke.

**Comment by jenius** [comment]
You could always just go with [a lighter framework](https://vuejs.org) :grin:

**Comment by FranzSkuffka** [comment]
I am going to build an E-Mail template editor. Do you recommend vue.js and have any experience with it? I saw it before and it looks really appealing.

**Comment by jenius** [comment]
Yes and yes. Use it with `vue-resource` and `vuex` for best results.

**Comment by FranzSkuffka** [comment]
Thanks, I will look into it. Had 2 solid days of angular2 PITA without any results.

**Comment by jenius** [comment]
As far as I've seen, thats how things tend to be with angular

**Comment by FranzSkuffka** [comment]
I won't let angular get between roots and me :heart:

**Comment by EnMod** [comment]
Don't mean to butt in, but would either of you like to share your Roots/Vue.js setup?  I'm learning Vue now and am curious as to the optimal setup with Roots.

**Comment by jenius** [comment]
@EnMod I'm not doing anything special with it, just using it the recommended way with jade. I use `vie-resource` for connection with the server.

**Comment by EnMod** [comment]
Ah ok, was making sure there weren't any crazy caveats.  Given that roots-mini will be using a Webpack core, I'm assuming Vue single file components might be usable within that ecosystem?

**Comment by jenius** [comment]
@EnMod yes, already working there 😁

**Comment by EnMod** [comment]
Ah I see!  Looks like I need to step it up :+1:

**Comment by FranzSkuffka** [comment]
No magic in my setup either, I restructure the application as I go. Usually I use it with roots-browserify to integrate with npm, but that's it.

**Comment by EnMod** [comment]
Very cool! Now if only I could understand why it is throwing this `Webpack failed to add entry for` error on my files...

**Comment by jenius** [comment]
Better to ask in http://gitter.im/jenius/roots. If that's happening something is likely severely misconfigured. Did you generate a new template to start? I'd start with that!
