### ISSUE TITLE
Add `ship.conf` to `.gitignores` by default.

### ISSUE THREAD

**Issue by FranzSkuffka** [jenius/roots#706]
As a built-in feature I would suggest ignoring the sensitive data generated through ship by default.

**Comment by jenius** [comment]
I'm entirely ok with adding this to the gitignore on [the default template](https://github.com/roots-dev/base), if you want to send in a PR!

**Comment by FranzSkuffka** [comment]
Just to note, I was intentionally filing this issue here because it is a part of roots' core and not inherent to a template. Opened a PR on the base template now.

**Comment by jenius** [comment]
Even making the compiler ignore it I'd suggest adding through the template, with `ignore` in `app.coffee`, rather than adding to core...
