### ISSUE TITLE
Npm warning when initializing new Roots project (jade@1.11.0)

### ISSUE THREAD

**Issue by ryanjbonnell** [jenius/roots#708]
When initializing a new project in Roots, the following warning is shown:

```shell
$ roots new example-project
```

> npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

This warning is caused by [Jade][1] being forced to [rename itself to Pug][2] :(

I'm running **Roots v4.0.1**.
```
$ roots -v
4.0.1
```

[1]: http://jade-lang.com/
[2]: https://github.com/pugjs/pug/issues/2184

**Comment by jenius** [comment]
We're going to have to deal with this for now, because `pug` has only released an alpha breaking version on npm, so the only stable option right now is still jade.

http://registry.npmjs.org/pug

Closing this for now, but we will update the dependency once there's a stable version of pug out!
