### ISSUE TITLE
Confused about `ignores` and `dump_dirs` configuration options

### ISSUE THREAD

**Issue by axelboc** [jenius/roots#710]
I'm quite confused about the `ignores` and `dump_dirs` configuration options. I'm having issues with the `watch` command going into an infinite compile loop (on Windows), and keep having to deal with files and folders being copied into the output folder for no good reason, so I'd like to get my head around these two options to make sure I'm using them properly.

From the Roots documentation:

> #### ignores
> An array containing minimatch strings that represent files or folder you wish to ignore from the compile process. Full globstar syntax supported. Automatically ignores package.json, node_modules, app.coffee and your output directory (wouldn't want to have it recursively compile itself!)

What do you mean by _ignore from the compile process_? Does this option control both the compiler and the watcher? Should CSS, JS and Jade partials that are imported/required from other files be ignored? What if I want them to be watched?

> #### dump_dirs
> Array of directories that will have their contents dumped into the output folder rather than compiling into the folder they are in.
> default: ['views', 'assets']

I don't understand this at all. Taking the `assets` folder for instance: on one hand I've got CSS and JS files which I obviously don't want dumped into the output folder (I want them to go through the compilation process), and on the other hand I have image files and other random assets (favicons, sitemap, Netlify's `_redirects` file, etc.) that I do want dumped into the output folder. Does this mean I should list the `assets` folder or not?

Also, for some reason, if I don't ignore files such as `.gitignore` or `npm-debug.log` in the root folder, they get copied into the output folder. Does this mean that files get copied whether or not they are processed by a compiler, and whether or not they are located inside one of the `dump_dirs` directories?

Clearly, my mental mental model of how these two options work is a complete blur! Any information would be greatly appreciated.

**Comment by jenius** [comment]
Hey @axelboc!

Thanks for writing such a clear and straightforward issue. I hope I'll be able to help with this one.

`ignores`, as the docs mention, are only ignored from the compile process, not the watcher. You can use `watcher_ignores` to update which files the watcher doesn't keep track of. These do have to be separate for a good reason, and much thought was put into this particular design pattern. Out of the box, partials are ignored from the compiler but not the watcher.

`dump_dirs` doesn't mean just copy the asset without processing, it basically means un-nest these assets from the folder listed in the array when putting them in the output. Sorry, I can totally see how the description is confusing, maybe you would be able to help suggest a more clear way? So basically, if you have `assets` in the `dump_dirs` array, then you have `assets/favicon.ico` and `assets.css/index.css` in the `assets` folder, in the output, they will be un-nested from the `assets` folder and just left at root, as `public/favicon.ico` and `public/css/index.css`. It doesn't have anything to do with compilation, it just deals with un-nesting nested folders from assets when going to the output.

As far as static files being copied, basically roots takes any non-ignored and non-compiled files and copies them over to the output. So if there's any file in your source that you do not want to be in the output, you must explicitly add it to the `ignores`.

Hope this helps, and let me know if I didn't do a good job explaining any of this and I can take another crack at it!

**Comment by axelboc** [comment]
Wow, thanks!

`dump_dirs` makes a lot more sense to me now; the concrete example you gave did the trick: `assets/css/index.css` gets compiled to `public/css/index.css ` instead of `public/assets/css/index.css`. Also, glad to hear that the watcher's ignores are now separate - it's a shame that the documentation is not up to date, though!

Here are a couple of follow-up questions:
- I had a look at `roots/config.coffee` and was wondering why `node_modules` is not ignored by default (it's in `watcher_ignores` but not in `ignores`). How does Roots know not to process the folder?
- You mentioned that partials are ignored by default. Is this still true? If I remove the globs (`views/**/_*` and `assets/css/_*`) from my own config, Roots compiles them. I think it's good if they're not, as I have a file that starts with an underscore in the assets folder which I want copied to the output folder, so if `**/_*`  were ignored, that file wouldn't get copied.

Regarding the fact that files have to be ignored in order for them not to be compiled/copied into the output folder; I can't help but wonder whether the other way around would make more sense (i.e. telling Roots which files to process), especially now that the watcher is completely independent.

Anyway, thanks to your clarifications, I was able to fix a few bugs in my configuration. Unfortunately, I'm still facing an infinite compile loop when I run `roots watch`. :cry: Is there a way to see which files the watcher thinks have changed. I tried the `debug` and `verbose` options, but nothing more gets logged to the console; just `compiling... done` over and over again. (Any reason why these options don't work by the way? It'd be so awesome if they printed which files Roots compiles and with which compilers! It'd be really helpful for debugging the config and understanding Roots' internals.)

**Comment by jenius** [comment]
Would love any help with the docs, [they are open source](https://github.com/carrot/roots-www) as is every part of roots!

First question, roots never reads any `node_modules` or `.git` folders, you can see [where it skips em here](https://github.com/jenius/roots/blob/d4c08230b5f6f723ab2bef3197caf83aae198d7b/lib/fs_parser.coffee#L71).

Second question, no, the default is in the base template. We purposely give users control over whether they want to use the partial pattern or not by not putting this in core.

For the third question about flipping things, from our experience the answer is no. This way of doing things is very frustrating, and results in really huge config files. Gulp/grunt etc work like this and you have seen how huge their configs get. If there's a file in your source, chances are you want it to be compiled somehow.

As for the debugging, it's tough on windows. Nobody that works on this has windows, so it is just not a priority for us at the moment. As for the verbose option, it should work, if not that is a bug that should be fixed! You can always pull roots down, `npm link`, and log the filename out from the compiler.

**Comment by axelboc** [comment]
It makes sense, thanks for clarifying all this! I'll take a look at the `verbose` option as you suggest, and try to debug the watcher issue. I've got my config under control now and I understand it, which is awesome! Thanks for your help.

**Comment by jenius** [comment]
No problem, glad I could help! Happy to answer any other questions if you've got em 😀
