### ISSUE TITLE
v1.roots.cx 500 Internal Server Error

### ISSUE THREAD

**Issue by ganar** [jenius/roots#712]
The documentation for V2 of roots is no longer online

**Comment by jenius** [comment]
Yeah I'm sorry about this! I'm not going to have the time to get it back online though unfortunately. If you still have a roots v2 project I'd recommend upgrading to a more recent version. If you have specific questions, I can try to help.

**Comment by ganar** [comment]
may I provide help on this issue? maybe those pages can run as static pages here, on github?

**Comment by jenius** [comment]
You can provide any help that you can! I just do not have any extra bandwidth that I can dedicate to this, unfortunately.

**Comment by ganar** [comment]
Were can I find the original docs in HTML? In which repo? I may be able to create a repo for them or fork them in my personal account and publish them in github as static pages, you can point v1.root.cx there. Would that be ok with you?

**Comment by jescalan** [comment]
Yup! https://github.com/jescalan/roots-www-old

**Comment by ganar** [comment]
Here is the documentation for Roots  2, running on github, it took a while, but everything is working:

http://ganar.github.io/roots-www-v1-docs/

I think that you can point v1.roots.cx to this place, or maybe host the pages that I corrected in http://github.com/jescalan/roots-www-old, whatever feels right to you. The idea is to not lose the documentation, too keep it viewable online.

Thanks for all your efforts with root.

Cheers

**Comment by jescalan** [comment]
You need to add a `CNAME` file to the repo for the domain to work when I point it there, see the docs here: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by ganar** [comment]
Hi Jeff:

I’m sorry for my delay in answering you. The CNAME configuration on my side is ready 

Cheers!

**Comment by jescalan** [comment]
@ganar the domain redirect is set up. `CNAME` for `v1.roots.cx` points to `ganar.github.io`

**Comment by ganar** [comment]
Great: It's working! I need to change a couple of things, but at least it is usable.
